#Requires -Version 5.1
<#
.SYNOPSIS
    OMMigrate-Reporting.psm1 -- HTML Report Generator

.DESCRIPTION
    Generates all four OMMigrate HTML reports. Each report is a
    fully self-contained single HTML file -- no external dependencies,
    no internet connection required, printable, and designed to serve
    as a professional client deliverable for IT consultants.

    Reports generated:
        Discovery_Report_YYYYMMDD.html
            Generated by Script 00. Shows all 26 accounts discovered,
            their classification tags, data file paths and sizes,
            folder tree summary, rules inventory, and the pre-migration
            action plan. The operator reviews this before any changes.

        Backup_Report_YYYYMMDD.html
            Generated by Script 01. Shows each PST backup -- file path,
            size, verification status, and checksum. Serves as the
            paper trail confirming backups exist before any account
            is touched.

        Migration_Report_YYYYMMDD.html
            Generated by Script 02. Shows each account's migration
            outcome -- removed POP3, added IMAP, connection verified,
            or skipped. Color-coded per account.

        Rollback_Report_YYYYMMDD.html
            Generated on demand or on failure. Documents what was
            completed, what failed, and what recovery steps apply.

    All reports share:
        - Dark professional theme (defined in OMMigrate-Core CSS)
        - Color-coded status badges (green/amber/red)
        - Summary stat cards at the top
        - Per-account detail tables
        - Full credit block in footer
        - Print stylesheet for client delivery

.NOTES
    -------------------------------------------------------------------------
    OutlookMailMigrator (OMMigrate)
    -------------------------------------------------------------------------
    Originator & Architect:    Kirk Shallcross - Shallcross Consulting
    Implementation Specialist: Anthropic Claude AI
    Inception Date:            May 2026
    Version:                   1.5.2
    -------------------------------------------------------------------------

    Requirements:
        PowerShell      : 5.1 or higher
        OMMigrate-Core  : Must be imported before this module
        No browser      : Reports render in any modern browser
        No internet     : All CSS and JS is inline -- fully self-contained

    Output:
        All reports are written to:
            $Global:OMMigrate.ReportPath\<ReportName>_YYYYMMDD.html

    Opening Reports:
        Reports are opened automatically via Open-FileInEditor
        (defined in OMMigrate-Core) which routes HTML files to the
        default browser.
#>

Set-StrictMode -Version Latest


# ============================================================
#  MODULE CONSTANTS
# ============================================================

# Tag badge CSS class mapping
$Script:TagBadgeClass = @{
    'POP3-STANDARD'     = 'badge-pop3'
    'POP3-ATTAMERITECH' = 'badge-pop3'
    'POP3-GMAIL'        = 'badge-pop3'
    'POP3-AWS'          = 'badge-pop3'
    'IMAP-ALREADY'      = 'badge-imap'
    'IMAP-GMAIL'        = 'badge-imap'
    'EXCHANGE-SKIP'     = 'badge-exchange'
    'UNKNOWN'           = 'badge-skip'
    # Standalone mounted PST archive stores (no registry account entry)
    'PST-ARCHIVE'       = 'badge-skip'
    # Converted tags -- POP3-* accounts that have been migrated to IMAP
    # These are computed at report time when MigrationDetail confirms already IMAP
    'IMAP-STANDARD'     = 'badge-imap'
    'IMAP-ATTAMERITECH' = 'badge-imap'
    'IMAP-AWS'          = 'badge-imap'
    # Post-migration state tags
    'IMAP-CONVERTED'    = 'badge-imap'
    'COMPLETE'          = 'badge-imap'
}

# Migration action badge class mapping
$Script:ActionBadgeClass = @{
    'MIGRATE'      = 'badge-pop3'
    'FOLDER-ONLY'  = 'badge-imap'
    'SKIP'         = 'badge-skip'
    'MANUAL'       = 'badge-exchange'
    # Computed at report time -- signals operator to update CSV
    # MIGRATED* = first re-run after successful migration (still shows MIGRATE in CSV)
    # COMPLETED* = subsequent runs (operator still hasn't updated CSV)
    'MIGRATED*'    = 'badge-update'
    'COMPLETED*'   = 'badge-update'
    # Final state -- folder migration and artifact migration complete
    'COMPLETE'     = 'badge-imap'
}

# Outcome status CSS class mapping
$Script:OutcomeClass = @{
    'SUCCESS'  = 'status-ok'
    'SKIPPED'  = 'status-skip'
    'FAILED'   = 'status-fail'
    'WARNING'  = 'status-warn'
    'PENDING'  = 'status-warn'
}

# Outcome icon mapping
$Script:OutcomeIcon = @{
    'SUCCESS'  = '&#10003;'    # OK
    'SKIPPED'  = '&#8212;'     # --
    'FAILED'   = '&#10007;'    # X
    'WARNING'  = '&#9888;'     # !
    'PENDING'  = '&#8230;'     # ...
}


# ============================================================
#  REGION: SHARED REPORT HELPERS
# ============================================================

function Get-ReportFilePath {
    <#
    .SYNOPSIS
        Builds a timestamped report file path in the Reports directory.

    .DESCRIPTION
        Constructs the full output path for a report file using the
        current date and the provided report name. Ensures the Reports
        directory exists before returning the path.

    .PARAMETER ReportName
        Short name for the report (e.g. 'Discovery', 'Backup').
        The timestamp and .html extension are appended automatically.

    .OUTPUTS
        [string] -- Full path to the report file.

    .EXAMPLE
        $path = Get-ReportFilePath -ReportName 'Discovery'
        # Returns: C:\...\Reports\Discovery_Report_20260521.html
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$ReportName
    )

    $datestamp  = Get-Date -Format 'yyyyMMdd_HHmmss'
    $fileName   = "${ReportName}_Report_${datestamp}.html"
    $reportPath = $Global:OMMigrate.ReportPath

    if (-not (Test-Path $reportPath)) {
        New-Item -ItemType Directory -Path $reportPath -Force | Out-Null
    }

    return Join-Path $reportPath $fileName
}


function New-BadgeHtml {
    <#
    .SYNOPSIS
        Returns an HTML badge span for a provider tag or action value.

    .DESCRIPTION
        Generates a styled inline badge matching the report's color
        scheme. Used in account tables to make tags visually distinct
        at a glance.

    .PARAMETER Text
        The text to display inside the badge.

    .PARAMETER CssClass
        Optional CSS class override. If omitted, class is looked up
        from the tag/action mapping tables.

    .PARAMETER Type
        Which mapping table to use: 'Tag' | 'Action' | 'Outcome'
        Default: Tag

    .OUTPUTS
        [string] -- HTML span string.

    .EXAMPLE
        New-BadgeHtml -Text 'POP3-STANDARD' -Type 'Tag'
        New-BadgeHtml -Text 'MIGRATE'       -Type 'Action'
        New-BadgeHtml -Text 'SUCCESS'       -Type 'Outcome'
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Text,

        [Parameter(Mandatory = $false)]
        [string]$CssClass = '',

        [Parameter(Mandatory = $false)]
        [ValidateSet('Tag','Action','Outcome')]
        [string]$Type = 'Tag'
    )

    if ([string]::IsNullOrEmpty($CssClass)) {
        $CssClass = switch ($Type) {
            'Tag'     { $Script:TagBadgeClass[$Text]    }
            'Action'  { $Script:ActionBadgeClass[$Text] }
            'Outcome' { $Script:OutcomeClass[$Text]     }
        }
        if (-not $CssClass) { $CssClass = 'badge-skip' }
    }

    return "<span class='badge $CssClass'>$Text</span>"
}


function New-OutcomeHtml {
    <#
    .SYNOPSIS
        Returns a colored outcome string with icon for use in tables.

    .DESCRIPTION
        Combines an icon character with the outcome text in a colored
        span. Used in Migration and Backup report tables to show
        per-account results clearly.

    .PARAMETER Outcome
        Outcome value: SUCCESS | SKIPPED | FAILED | WARNING | PENDING

    .PARAMETER Detail
        Optional additional detail text shown after the outcome.

    .OUTPUTS
        [string] -- HTML string.

    .EXAMPLE
        New-OutcomeHtml -Outcome 'SUCCESS' -Detail 'Connected in 4.2s'
        New-OutcomeHtml -Outcome 'FAILED'  -Detail 'Server refused connection'
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [ValidateSet('SUCCESS','SKIPPED','FAILED','WARNING','PENDING')]
        [string]$Outcome,

        [Parameter(Mandatory = $false)]
        [string]$Detail = ''
    )

    $cssClass = $Script:OutcomeClass[$Outcome]
    $icon     = $Script:OutcomeIcon[$Outcome]
    $detail   = if ($Detail) { " <span style='color:var(--text-muted);font-size:11px'>$Detail</span>" } else { '' }

    return "<span class='$cssClass'>$icon $Outcome</span>$detail"
}


function New-AlertHtml {
    <#
    .SYNOPSIS
        Returns a styled alert box for inclusion in report sections.

    .DESCRIPTION
        Generates an info, warning, or success alert block used in
        reports to highlight important notes, prerequisites, or
        warnings that the operator needs to see.

    .PARAMETER Message
        The alert message text.

    .PARAMETER Type
        Alert style: 'info' | 'warn' | 'ok'
        Default: info

    .OUTPUTS
        [string] -- HTML string.

    .EXAMPLE
        New-AlertHtml -Message 'Review folder_map.csv to set Server/Local destinations after Script 01.' -Type 'warn'
        New-AlertHtml -Message 'All 13 backups verified successfully.' -Type 'ok'
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message,

        [Parameter(Mandatory = $false)]
        [ValidateSet('info','warn','ok')]
        [string]$Type = 'info'
    )

    return "<div class='alert alert-$Type'>$Message</div>"
}


function New-AccountTableHtml {
    <#
    .SYNOPSIS
        Builds a styled HTML table from an array of account objects.

    .DESCRIPTION
        Generates the per-account detail table used in Discovery,
        Migration, and Rollback reports. Columns shown depend on
        the report context (ReportType parameter).

        Columns included per report type:
            Discovery  : Email, DisplayName, Tag, Action, Server, Port,
                         DataFile, DataSize, Notes
            Backup     : Email, Tag, PSTPath, BackupPath, Size, Status
            Migration  : Email, Tag, Action, ImapServer, Outcome, Detail
            Rollback   : Email, Tag, CompletedStep, Outcome, RecoveryNote

    .PARAMETER Accounts
        Array of account objects to render.

    .PARAMETER ReportType
        Which column set to render: Discovery | Backup | Migration | Rollback

    .OUTPUTS
        [string] -- HTML table string.

    .EXAMPLE
        $tableHtml = New-AccountTableHtml -Accounts $accounts -ReportType 'Discovery'
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [array]$Accounts,

        [Parameter(Mandatory = $true)]
        [ValidateSet('Discovery','Backup','Migration','Rollback')]
        [string]$ReportType
    )

    $Accounts = @($Accounts)
    if (-not $Accounts -or $Accounts.Count -eq 0) {
        return "<p style='color:var(--text-muted);font-style:italic'>No accounts to display.</p>"
    }

    # -- Build column headers per report type ------------------
    $headers = switch ($ReportType) {
        'Discovery' {
            @('Email Address','Display Name','Tag','Action',
              'Server','Port','Data File','Size','Notes')
        }
        'Backup' {
            @('Email Address','Tag','Source PST','Backup File','Size','Status')
        }
        'Migration' {
            @('Email Address','Tag','Action','IMAP Server','Port','Outcome','Detail')
        }
        'Rollback' {
            @('Email Address','Tag','Last Step','Outcome','Recovery Note')
        }
    }

    $headerHtml = ($headers | ForEach-Object { "<th>$_</th>" }) -join ''

    # -- Build rows --------------------------------------------
    $rowsHtml = ''
    foreach ($account in $Accounts) {
        $cells = switch ($ReportType) {
            'Discovery' {
                $tagBadge    = New-BadgeHtml -Text $account.ProviderTag    -Type 'Tag'
                $actionBadge = New-BadgeHtml -Text $account.MigrationAction -Type 'Action'
                $server      = if ($account.IncomingServer) { $account.IncomingServer } else { '<span style="color:var(--text-muted)">--</span>' }
                $port        = if ($account.IncomingPort -gt 0) { $account.IncomingPort } else { '<span style="color:var(--text-muted)">--</span>' }
                $dataFilePath = if ($account.PSTPath) { $account.PSTPath }
                               elseif ($account.OSTPath) { $account.OSTPath }
                               else { "" }
                $pstFile = if ($dataFilePath) {
                    "<span title='Hover shows full path: $dataFilePath' style='cursor:help;border-bottom:1px dotted'>" +
                    [System.IO.Path]::GetFileName($dataFilePath) +
                    "</span>"
                } else { '<span style="color:var(--text-muted)">--</span>' }
                $size        = if ($account.DataFileSizeFormatted) { $account.DataFileSizeFormatted } else { '<span style="color:var(--text-muted)">--</span>' }
                $notes       = if ($account.Notes) {
                    "<span style='font-size:11px;color:var(--text-muted)'>$($account.Notes)</span>"
                } else { '' }

                @(
                    "<td><strong>$($account.EmailAddress)</strong></td>",
                    "<td>$($account.DisplayName)</td>",
                    "<td>$tagBadge</td>",
                    "<td>$actionBadge</td>",
                    "<td>$server</td>",
                    "<td>$port</td>",
                    "<td>$pstFile</td>",
                    "<td>$size</td>",
                    "<td>$notes</td>"
                ) -join ''
            }

            'Backup' {
                $tagBadge   = New-BadgeHtml -Text $account.ProviderTag -Type 'Tag'
                $status     = if ($account.BackupStatus) { $account.BackupStatus } else { 'PENDING' }
                $outcomeHtml = New-OutcomeHtml -Outcome $status `
                                               -Detail $account.BackupDetail
                $srcFile    = if ($account.PSTPath) {
                    [System.IO.Path]::GetFileName($account.PSTPath)
                } elseif ($account.OSTPath) {
                    # IMAP-ALREADY account -- source was an OST exported to PST via COM
                    "<span title='Full path: $($account.OSTPath)' style='cursor:help;border-bottom:1px dotted'>" +
                    [System.IO.Path]::GetFileName($account.OSTPath) +
                    "</span> <span style='font-size:11px;color:var(--text-muted)'>(OST&rarr;PST)</span>"
                } else { '<span style="color:var(--text-muted)">Not found</span>' }
                $bkpFile    = if ($account.BackupPath) {
                    [System.IO.Path]::GetFileName($account.BackupPath)
                } else { '<span style="color:var(--text-muted)">--</span>' }
                $size       = if ($account.BackupSizeFormatted) { $account.BackupSizeFormatted } else { '--' }

                @(
                    "<td><strong>$($account.EmailAddress)</strong></td>",
                    "<td>$tagBadge</td>",
                    "<td><code>$srcFile</code></td>",
                    "<td><code>$bkpFile</code></td>",
                    "<td>$size</td>",
                    "<td>$outcomeHtml</td>"
                ) -join ''
            }

            'Migration' {
                # Determine effective display tag -- if the live Outlook check confirmed
                # this account is already IMAP, show its current protocol state (IMAP-*)
                # rather than the original CSV tag (POP3-*). This reflects what the
                # account actually is now, not what it was before migration.
                $displayTag = $account.ProviderTag
                if ($account.MigrationDetail -match 'Already IMAP' -or
                    $account.MigrationDetail -match 'already IMAP') {
                    $displayTag = $account.ProviderTag -replace '^POP3-', 'IMAP-'
                }

                # Determine effective display action -- if already IMAP, show MIGRATED*
                # or COMPLETED* instead of MIGRATE to signal the operator to update the CSV.
                # MIGRATED* = MigrationOutcome is SKIPPED (first re-run detection)
                # COMPLETED* = MigrationAction is still MIGRATE but account was auto-skipped
                #              on a subsequent run (operator still hasn't updated CSV)
                # Both use badge-update (amber) to make the action item visually distinct.
                $displayAction = $account.MigrationAction
                if ($account.MigrationDetail -match 'Already IMAP' -or
                    $account.MigrationDetail -match 'already IMAP') {
                    # First detection shows MIGRATED*, repeated runs show COMPLETED*
                    $displayAction = if ($account.MigrationAction -eq 'MIGRATE') {
                        'MIGRATED*'
                    } else {
                        'COMPLETED*'
                    }
                }

                $tagBadge    = New-BadgeHtml -Text $displayTag    -Type 'Tag'
                $actionBadge = New-BadgeHtml -Text $displayAction  -Type 'Action'
                $outcome     = if ($account.MigrationOutcome) { $account.MigrationOutcome } else { 'PENDING' }
                # NOTE (fixed 2026-06-18): -Detail intentionally omitted here. The
                # Migration table renders its own dedicated "Detail" column from
                # $account.MigrationDetail a few lines below -- passing the same
                # text into -Detail here duplicated it inside the Outcome cell too
                # (every row showed "Migrated=N | Items=N | Failed=N" twice).
                # Backup and Rollback call sites below are untouched -- they don't
                # have a separate Detail column, so New-OutcomeHtml's built-in
                # -Detail rendering is still the right behavior for them.
                $outcomeHtml = New-OutcomeHtml -Outcome $outcome
                $imapServer  = if ($account.NewImapServer) { $account.NewImapServer } else { '<span style="color:var(--text-muted)">--</span>' }
                $imapPort    = if ($account.NewImapPort -gt 0) { $account.NewImapPort } else { '<span style="color:var(--text-muted)">--</span>' }

                @(
                    "<td><strong>$($account.EmailAddress)</strong></td>",
                    "<td>$tagBadge</td>",
                    "<td>$actionBadge</td>",
                    "<td>$imapServer</td>",
                    "<td>$imapPort</td>",
                    "<td>$outcomeHtml</td>",
                    "<td><span style='font-size:11px'>$($account.MigrationDetail)</span></td>"
                ) -join ''
            }

            'Rollback' {
                $tagBadge    = New-BadgeHtml -Text $account.ProviderTag -Type 'Tag'
                $outcome     = if ($account.RollbackOutcome) { $account.RollbackOutcome } else { 'PENDING' }
                $outcomeHtml = New-OutcomeHtml -Outcome $outcome
                $lastStep    = if ($account.LastCompletedStep) { $account.LastCompletedStep } else { '--' }
                $recovery    = if ($account.RecoveryNote) {
                    "<span style='font-size:11px;color:var(--yellow)'>$($account.RecoveryNote)</span>"
                } else { '--' }

                @(
                    "<td><strong>$($account.EmailAddress)</strong></td>",
                    "<td>$tagBadge</td>",
                    "<td>$lastStep</td>",
                    "<td>$outcomeHtml</td>",
                    "<td>$recovery</td>"
                ) -join ''
            }
        }

        $rowsHtml += "<tr>$cells</tr>`n"
    }

    # -- Totals row per report type ----------------------------
    $acctTotal    = @($Accounts).Count
    $tfootRowHtml = switch ($ReportType) {
        'Discovery' {
            @"
  <tr style='background:var(--surface-2,rgba(0,0,0,0.06));font-weight:600;border-top:2px solid var(--border)'>
    <td colspan='9'><strong>Total: $acctTotal account(s)</strong></td>
  </tr>
"@
        }
        'Backup' {
            $bkSucceeded = @($Accounts | Where-Object { $_.BackupStatus -eq 'SUCCESS' }).Count
            $bkFailed    = @($Accounts | Where-Object { $_.BackupStatus -eq 'FAILED'  }).Count
            $bkSkipped   = @($Accounts | Where-Object { $_.BackupStatus -eq 'SKIPPED' }).Count
            @"
  <tr style='background:var(--surface-2,rgba(0,0,0,0.06));font-weight:600;border-top:2px solid var(--border)'>
    <td colspan='5'><strong>Total: $acctTotal account(s)</strong></td>
    <td><span class='status-ok'>$bkSucceeded OK</span>&nbsp; <span class='status-warn'>$bkFailed Failed</span>&nbsp; <span class='status-skip'>$bkSkipped Skipped</span></td>
  </tr>
"@
        }
        'Migration' {
            $mgSucceeded = @($Accounts | Where-Object { $_.MigrationOutcome -eq 'SUCCESS' }).Count
            $mgFailed    = @($Accounts | Where-Object { $_.MigrationOutcome -eq 'FAILED'  }).Count
            $mgSkipped   = @($Accounts | Where-Object { $_.MigrationOutcome -eq 'SKIPPED' }).Count
            $mgWarned    = @($Accounts | Where-Object { $_.MigrationOutcome -eq 'WARNING' }).Count
            @"
  <tr style='background:var(--surface-2,rgba(0,0,0,0.06));font-weight:600;border-top:2px solid var(--border)'>
    <td colspan='5'><strong>Total: $acctTotal account(s)</strong></td>
    <td><span class='status-ok'>$mgSucceeded OK</span>&nbsp; <span class='status-warn'>$mgFailed Failed</span>&nbsp; <span class='status-skip'>$mgSkipped Skipped</span>&nbsp; <span style='color:var(--yellow)'>$mgWarned Warned</span></td>
    <td></td>
  </tr>
"@
        }
        'Rollback' {
            $rbCompleted = @($Accounts | Where-Object { $_.RollbackOutcome -eq 'SUCCESS' }).Count
            $rbFailed    = @($Accounts | Where-Object { $_.RollbackOutcome -eq 'FAILED'  }).Count
            $rbPending   = @($Accounts | Where-Object { $_.RollbackOutcome -eq 'PENDING' -or -not $_.RollbackOutcome }).Count
            @"
  <tr style='background:var(--surface-2,rgba(0,0,0,0.06));font-weight:600;border-top:2px solid var(--border)'>
    <td colspan='3'><strong>Total: $acctTotal account(s)</strong></td>
    <td><span class='status-ok'>$rbCompleted Completed</span>&nbsp; <span class='status-warn'>$rbFailed Failed</span>&nbsp; <span class='status-skip'>$rbPending Pending</span></td>
    <td></td>
  </tr>
"@
        }
        default { '' }
    }

    # Build footer note -- only shown for Migration report when any account
    # has MIGRATED* or COMPLETED* action badge (signals CSV update needed)
    $footerNote = ''
    if ($ReportType -eq 'Migration') {
        $needsUpdate = @($Accounts | Where-Object {
            $_.MigrationDetail -match 'Already IMAP' -or
            $_.MigrationDetail -match 'already IMAP'
        })
        if ($needsUpdate.Count -gt 0) {
            $footerNote = @"
<p style='font-size:11px;color:var(--text-muted);margin-top:8px;line-height:1.6'>
* <strong style='color:#e3b341'>MIGRATED*</strong> and
<strong style='color:#e3b341'>COMPLETED*</strong> indicate accounts that have been
successfully converted to IMAP and were detected automatically on re-run.
To remove these from future migration runs, update
<code>Config\migration_accounts.csv</code> and make the following three changes
for each flagged account:
<br>&nbsp;&nbsp;1. Change <code>MigrationAction</code> from <code>MIGRATE</code> to <code>FOLDER-ONLY</code>
<br>&nbsp;&nbsp;2. Change <code>ProviderTag</code> from <code>POP3-*</code> to <code>IMAP-ALREADY</code>
<br>&nbsp;&nbsp;3. Change <code>AccountType</code> from <code>POP3</code> to <code>IMAP</code>
<br><strong>Do not set MigrationAction to SKIP</strong> -- Script 03 still needs to process
these accounts for folder migration.
</p>
"@
        }
    }

    return @"
<table>
  <thead><tr>$headerHtml</tr></thead>
  <tbody>
$rowsHtml  </tbody>
  <tfoot>
$tfootRowHtml  </tfoot>
</table>
$footerNote
"@
}


function New-FolderSummaryHtml {
    <#
    .SYNOPSIS
        Builds an HTML summary table of the folder tree for the
        Discovery report.

    .DESCRIPTION
        Renders a condensed view of the folder inventory -- store
        names, folder counts, item counts, and suggested destination
        (Server/Local). Full folder detail is in folder_map.csv.

    .PARAMETER Folders
        Array of folder objects from Get-FolderTree.

    .OUTPUTS
        [string] -- HTML table string.

    .EXAMPLE
        $folderHtml = New-FolderSummaryHtml -Folders $folders
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [array]$Folders
    )

    $Folders = @($Folders)
    if (-not $Folders -or $Folders.Count -eq 0) {
        return "<p style='color:var(--text-muted);font-style:italic'>No folders enumerated.</p>"
    }

    # Group by store for summary
    $byStore = $Folders | Group-Object -Property StoreName

    $headerHtml = '<th>Store / Account</th><th>Type</th><th>Folders</th><th>Total Items</th><th>Server</th><th>Local</th>'

    $rowsHtml = ''
    foreach ($storeGroup in $byStore) {
        $storeFolders  = $storeGroup.Group
        $storeType     = ($storeFolders | Select-Object -First 1).StoreType
        $totalFolders  = @($storeFolders).Count
        $totalItems    = ($storeFolders | Measure-Object -Property ItemCount -Sum).Sum
        $serverCount   = @($storeFolders | Where-Object { $_ -and $_.PSObject.Properties['Destination'] -and $_.Destination -eq 'Server' }).Count
        $localCount    = @($storeFolders | Where-Object { $_ -and $_.PSObject.Properties['Destination'] -and $_.Destination -eq 'Local'  }).Count

        $typeClass = switch ($storeType) {
            'PST'      { 'badge-pop3'      }
            'OST'      { 'badge-imap'      }
            'Exchange' { 'badge-exchange'  }
            default    { 'badge-skip'      }
        }

        $rowsHtml += @"
  <tr>
    <td><strong>$($storeGroup.Name)</strong></td>
    <td><span class='badge $typeClass'>$storeType</span></td>
    <td>$totalFolders</td>
    <td>$totalItems</td>
    <td><span class='status-ok'>$serverCount</span></td>
    <td><span style='color:var(--accent)'>$localCount</span></td>
  </tr>
"@
    }

    # -- Totals row -------------------------------------------
    $grandFolders = ($byStore | ForEach-Object { $_.Group } | Measure-Object).Count
    $grandItems   = ($byStore | ForEach-Object { $_.Group } | Measure-Object -Property ItemCount -Sum).Sum
    $grandServer  = @($byStore | ForEach-Object { $_.Group } | Where-Object { $_ -and $_.PSObject.Properties['Destination'] -and $_.Destination -eq 'Server' }).Count
    $grandLocal   = @($byStore | ForEach-Object { $_.Group } | Where-Object { $_ -and $_.PSObject.Properties['Destination'] -and $_.Destination -eq 'Local'  }).Count

    $folderTfootHtml = @"
  <tr style='background:var(--surface-2,rgba(0,0,0,0.06));font-weight:600;border-top:2px solid var(--border)'>
    <td><strong>Total</strong></td>
    <td><span style='color:var(--text-muted)'>All Stores</span></td>
    <td><strong>$grandFolders</strong></td>
    <td><strong>$grandItems</strong></td>
    <td><span class='status-ok'><strong>$grandServer</strong></span></td>
    <td><span style='color:var(--accent)'><strong>$grandLocal</strong></span></td>
  </tr>
"@

    return @"
<table>
  <thead><tr>$headerHtml</tr></thead>
  <tbody>
$rowsHtml  </tbody>
  <tfoot>
$folderTfootHtml  </tfoot>
</table>
"@
}


function New-RulesSummaryHtml {
    <#
    .SYNOPSIS
        Builds an HTML summary table of Outlook Rules for the
        Discovery report.

    .DESCRIPTION
        Renders the rules inventory in a compact table. Rules that
        have folder targets (NeedsFolderUpdate = true) are highlighted
        in amber -- these are the rules Script 03 must update.

    .PARAMETER Rules
        Array of rule objects from Get-OutlookRules.

    .OUTPUTS
        [string] -- HTML table string.

    .EXAMPLE
        $rulesHtml = New-RulesSummaryHtml -Rules $rules
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [array]$Rules
    )

    $Rules = @($Rules)
    if (-not $Rules -or $Rules.Count -eq 0) {
        return "<p style='color:var(--text-muted);font-style:italic'>No Outlook Rules found.</p>"
    }

    $headerHtml = '<th>#</th><th>Rule Name</th><th>Type</th><th>Enabled</th><th>Conditions</th><th>Actions</th><th>Folder Target</th><th>Update Needed</th>'

    $rowsHtml = ''
    $i = 1
    foreach ($rule in ($Rules | Sort-Object ExecutionOrder)) {
        $enabledHtml = if ($rule.IsEnabled) {
            "<span class='status-ok'>&#10003; Yes</span>"
        } else {
            "<span class='status-skip'>&#8212; No</span>"
        }

        $updateHtml = if ($rule.NeedsFolderUpdate) {
            "<span class='status-warn'>&#9888; Yes -- folder will be updated by Script 03</span>"
        } else {
            "<span class='status-skip'>&#8212; No</span>"
        }

        # HTML-encode all rule-data-derived fields before rendering -- rule
        # names, folder paths, and condition/action summaries can legitimately
        # contain '&', '<', '>' (e.g. an "AT&T" sender condition), which would
        # otherwise corrupt the table markup. [System.Net.WebUtility]::HtmlEncode
        # is part of System.dll, always loaded, no Add-Type required. Added
        # 2026-06-27 alongside the same fix in the manually-added-rules block.
        $encodedRuleName = [System.Net.WebUtility]::HtmlEncode($rule.RuleName)
        $encodedRuleType = [System.Net.WebUtility]::HtmlEncode($rule.RuleType)

        $folderTarget = if ($rule.TargetFolderPath) {
            "<code style='font-size:11px'>$([System.Net.WebUtility]::HtmlEncode($rule.TargetFolderPath))</code>"
        } else {
            "<span style='color:var(--text-muted)'>--</span>"
        }

        $conditions = if ($rule.Conditions) {
            "<span style='font-size:11px'>$([System.Net.WebUtility]::HtmlEncode($rule.Conditions))</span>"
        } else { '--' }

        $actions = if ($rule.Actions) {
            "<span style='font-size:11px'>$([System.Net.WebUtility]::HtmlEncode($rule.Actions))</span>"
        } else { '--' }

        # Highlight rows for rules needing folder updates
        $rowStyle = if ($rule.NeedsFolderUpdate) {
            " style='background:rgba(210,153,34,0.05)'"
        } else { '' }

        $rowsHtml += @"
  <tr$rowStyle>
    <td>$i</td>
    <td><strong>$encodedRuleName</strong></td>
    <td>$encodedRuleType</td>
    <td>$enabledHtml</td>
    <td>$conditions</td>
    <td>$actions</td>
    <td>$folderTarget</td>
    <td>$updateHtml</td>
  </tr>
"@
        $i++
    }

    # -- Totals row -------------------------------------------
    $totalRules       = @($Rules).Count
    $totalEnabled     = @($Rules | Where-Object { $_.IsEnabled }).Count
    $totalWithTarget  = @($Rules | Where-Object { $_.TargetFolderPath }).Count
    $totalNeedUpdate  = @($Rules | Where-Object { $_.NeedsFolderUpdate }).Count

    $rulesTfootHtml = @"
  <tr style='background:var(--surface-2,rgba(0,0,0,0.06));font-weight:600;border-top:2px solid var(--border)'>
    <td><strong>$totalRules</strong></td>
    <td><strong>Total Rules</strong></td>
    <td><span style='color:var(--text-muted)'>--</span></td>
    <td><strong>$totalEnabled</strong> enabled</td>
    <td><span style='color:var(--text-muted)'>--</span></td>
    <td><span style='color:var(--text-muted)'>--</span></td>
    <td><strong>$totalWithTarget</strong> with target</td>
    <td><strong>$totalNeedUpdate</strong> need update</td>
  </tr>
"@

    return @"
<table>
  <thead><tr>$headerHtml</tr></thead>
  <tbody>
$rowsHtml  </tbody>
  <tfoot>
$rulesTfootHtml  </tfoot>
</table>
"@
}


# -- Additive function: per-store Rules Processing Detail table --
# Built for the Script 03 Migration Report enrichment. Unlike
# New-RulesSummaryHtml above (which lists every individual rule for the
# Script 00 Discovery report), this summarizes outcomes ONE ROW PER STORE/
# ACCOUNT -- appropriate for a 600+ rule environment where a per-rule table
# would make the report unreadably long. Administrator confirmed this granularity
# (per-store detail + aggregate summary grid) on 2026-06-18.
function New-RulesStoreSummaryHtml {
    <#
    .SYNOPSIS
        Builds an HTML summary table of rules-processing outcomes,
        one row per Outlook store/account, for the Migration Report.

    .DESCRIPTION
        Renders Created / Skipped / Failed / StopProcessing Set / 
        StopProcessing Failed counts per store. Intended to give an
        admin a single-screen view of which accounts had issues without
        listing all 600+ individual rules across a large environment.

    .PARAMETER StoreSummary
        Array of PSCustomObjects, each with: StoreName, Created, Skipped,
        Failed, StopProcessingSet, StopProcessingFailed. Built by Script 03
        as $Script:RulesStoreSummary.

    .OUTPUTS
        [string] -- HTML table string.

    .EXAMPLE
        $tableHtml = New-RulesStoreSummaryHtml -StoreSummary $Script:RulesStoreSummary
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [array]$StoreSummary
    )

    $StoreSummary = @($StoreSummary)
    if (-not $StoreSummary -or $StoreSummary.Count -eq 0) {
        return "<p style='color:var(--text-muted);font-style:italic'>No per-store rules data available.</p>"
    }

    $headerHtml = '<th>Store / Account</th><th>Created</th><th>Skipped</th><th>Failed</th>' +
                  '<th>StopProcessing Set</th><th>StopProcessing Needs Manual Fix</th>'

    $rowsHtml = ''
    foreach ($row in ($StoreSummary | Sort-Object StoreName)) {

        # -- Additive: distinct rendering for the primary-store "not
        # processed this run" row (NotProcessed=$true). This is NOT a
        # failure -- it means the COM Item() ceiling prevented this store
        # from being touched at all this pass. Rendering it through the
        # normal Created/Skipped/Failed/StopProcessing columns (all zero)
        # would misleadingly read as "nothing wrong here". Original
        # per-row rendering below (else branch) is unchanged.
        if ($row.PSObject.Properties.Match('NotProcessed').Count -gt 0 -and $row.NotProcessed) {
            $rowsHtml += @"
  <tr style='background:rgba(88,166,255,0.05)'>
    <td><strong>$($row.StoreName)</strong></td>
    <td colspan='5'><span style='color:var(--accent)'>Not processed this run</span> -- COM Item() enumeration ceiling at this rule count. Rules retain StopProcessing via original .rwz import; manual remediation via Outlook's Rules and Alerts UI if changes are needed this pass.</td>
  </tr>
"@
            continue
        }

        $failedHtml = if ($row.Failed -gt 0) {
            "<span class='status-warn'>$($row.Failed)</span>"
        } else {
            "<span style='color:var(--text-muted)'>0</span>"
        }

        $spFailedHtml = if ($row.StopProcessingFailed -gt 0) {
            "<span class='status-warn'>$($row.StopProcessingFailed)</span>"
        } else {
            "<span style='color:var(--text-muted)'>0</span>"
        }

        # Highlight rows that need admin attention (rule creation failures or
        # manual StopProcessing fixes needed) -- same amber-tint convention
        # used by New-RulesSummaryHtml above.
        $rowStyle = if ($row.Failed -gt 0 -or $row.StopProcessingFailed -gt 0) {
            " style='background:rgba(210,153,34,0.05)'"
        } else { '' }

        $rowsHtml += @"
  <tr$rowStyle>
    <td><strong>$($row.StoreName)</strong></td>
    <td>$($row.Created)</td>
    <td>$($row.Skipped)</td>
    <td>$failedHtml</td>
    <td>$($row.StopProcessingSet)</td>
    <td>$spFailedHtml</td>
  </tr>
"@
    }

    # -- Totals row -------------------------------------------
    $totalCreated  = ($StoreSummary | Measure-Object -Property Created -Sum).Sum
    $totalSkipped  = ($StoreSummary | Measure-Object -Property Skipped -Sum).Sum
    $totalFailed   = ($StoreSummary | Measure-Object -Property Failed -Sum).Sum
    $totalSpSet    = ($StoreSummary | Measure-Object -Property StopProcessingSet -Sum).Sum
    $totalSpFailed = ($StoreSummary | Measure-Object -Property StopProcessingFailed -Sum).Sum

    # -- Additive: split the store count label so "not processed this run"
    # stores (e.g. the primary/ameritech store) are called out distinctly
    # from stores that actually had Created/Skipped/Failed/StopProcessing
    # activity this pass. A flat "$count store(s)" total was ambiguous --
    # easy to misread as "N stores all had rule activity" when one or more
    # of them may have been structurally bypassed instead.
    $notProcessedStoreCount = @($StoreSummary | Where-Object {
        $_.PSObject.Properties.Match('NotProcessed').Count -gt 0 -and $_.NotProcessed
    }).Count
    $processedStoreCount = $StoreSummary.Count - $notProcessedStoreCount
    $storeCountLabel = if ($notProcessedStoreCount -gt 0) {
        "$processedStoreCount store(s) processed, $notProcessedStoreCount not processed"
    } else {
        "$($StoreSummary.Count) store(s)"
    }

    $storeTfootHtml = @"
  <tr style='background:var(--surface-2,rgba(0,0,0,0.06));font-weight:600;border-top:2px solid var(--border)'>
    <td><strong>$storeCountLabel</strong></td>
    <td><strong>$totalCreated</strong></td>
    <td><strong>$totalSkipped</strong></td>
    <td><strong>$totalFailed</strong></td>
    <td><strong>$totalSpSet</strong></td>
    <td><strong>$totalSpFailed</strong></td>
  </tr>
"@

    return @"
<table>
  <thead><tr>$headerHtml</tr></thead>
  <tbody>
$rowsHtml  </tbody>
  <tfoot>
$storeTfootHtml  </tfoot>
</table>
"@
}


function New-PrerequisiteListHtml {
    <#
    .SYNOPSIS
        Builds an HTML prerequisite checklist for accounts that
        require manual steps before migration.

    .DESCRIPTION
        Renders a per-account checklist of prerequisites the operator
        must complete before running migration scripts. Used in the
        Discovery report to highlight Ameritech Secure Mail Key
        requirements, AWS SES credential requirements, etc.

    .PARAMETER Accounts
        Array of account objects. Only accounts with PreRequisites
        entries are included.

    .OUTPUTS
        [string] -- HTML string, or empty if no prerequisites exist.

    .EXAMPLE
        $prereqHtml = New-PrerequisiteListHtml -Accounts $accounts
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [array]$Accounts
    )

    $accountsWithPrereqs = $Accounts | Where-Object {
        $_.PreRequisites -and @($_.PreRequisites).Count -gt 0
    }

    if (-not $accountsWithPrereqs -or @($accountsWithPrereqs).Count -eq 0) {
        return ''
    }

    $html = ''
    foreach ($account in $accountsWithPrereqs) {
        $items = ($account.PreRequisites | ForEach-Object {
            "<li style='margin-bottom:6px'>$_</li>"
        }) -join ''

        $html += @"
<div style='margin-bottom:16px'>
  <div style='font-weight:600;color:var(--text);margin-bottom:6px'>
    <span class='badge badge-pop3'>$($account.ProviderTag)</span>
    &nbsp; $($account.EmailAddress)
  </div>
  <ul style='color:var(--text-muted);font-size:13px;padding-left:20px;margin:0'>
    $items
  </ul>
</div>
"@
    }

    return $html
}


# ============================================================
#  REGION: DISCOVERY REPORT (Script 00)
# ============================================================

function New-DiscoveryReport {
    <#
    .SYNOPSIS
        Generates the Discovery HTML report from Script 00 results.

    .DESCRIPTION
        Produces a comprehensive pre-migration inventory report showing:
            - Summary statistics (total accounts, accounts to migrate,
              already IMAP, Exchange skipped, data file sizes)
            - Full account inventory table with classification tags
            - Folder tree summary by store
            - Outlook Rules inventory with folder-update flags
            - Prerequisite checklist for special-case accounts
            - Action plan -- what Scripts 01-03 will do

        This is the primary operator review document. The operator
        should read this report carefully and confirm all information
        is correct before running Script 01.

    .PARAMETER Accounts
        Array of classified account objects from Registry discovery.

    .PARAMETER Summary
        Account summary object from Get-AccountSummary.

    .PARAMETER Folders
        Array of folder objects from Get-FolderTree (optional).

    .PARAMETER Rules
        Array of rule objects from Get-OutlookRules (optional).

    .PARAMETER ProfileName
        Name of the Outlook profile that was scanned.

    .OUTPUTS
        [string] -- Path to the generated HTML report file.

    .EXAMPLE
        $reportPath = New-DiscoveryReport `
            -Accounts    $accounts `
            -Summary     $summary `
            -Folders     $folders `
            -Rules       $rules `
            -ProfileName 'Outlook'
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [array]$Accounts,

        [Parameter(Mandatory = $true)]
        [PSCustomObject]$Summary,

        [Parameter(Mandatory = $false)]
        [array]$Folders = @(),

        [Parameter(Mandatory = $false)]
        [array]$Rules = @(),

        [Parameter(Mandatory = $false)]
        [string]$ProfileName = 'Default'
    )

    Write-OMMigrateLog -Message 'Generating Discovery Report...' -Level INFO

    $reportFile = Get-ReportFilePath -ReportName 'Discovery'

    # -- Stat grid ---------------------------------------------
    $stats = [ordered]@{
        'Total Accounts'    = $Summary.Total
        'To Migrate'        = $Summary.ToMigrate
        'Already IMAP'      = $Summary.FolderOnly
        'Exchange (Skip)'   = $Summary.Skipped
        'Manual Review'     = $Summary.Manual
        'Total Data Size'   = $Summary.TotalDataSizeFormatted
    }
    $statGridHtml = Get-HtmlStatGrid -Stats $stats

    # -- Alerts ------------------------------------------------
    $alertsHtml = ''

    if ($Summary.RequiresSecureKey -gt 0) {
        $alertsHtml += New-AlertHtml -Type 'warn' -Message (
            "&#9888;&nbsp; <strong>$($Summary.RequiresSecureKey) account(s)</strong> require a " +
            "Secure Mail Key (app password) to be generated before migration. " +
            "See the Prerequisites section below."
        )
    }

    if ($Summary.HasAWSSES -gt 0) {
        $alertsHtml += New-AlertHtml -Type 'warn' -Message (
            "&#9888;&nbsp; <strong>$($Summary.HasAWSSES) account(s)</strong> use AWS SES for " +
            "outbound SMTP. AWS SES SMTP credentials must be re-entered " +
            "when Outlook prompts during IMAP account setup."
        )
    }

    if ($Summary.WithPSTMissing -gt 0) {
        $alertsHtml += New-AlertHtml -Type 'warn' -Message (
            "&#9888;&nbsp; <strong>$($Summary.WithPSTMissing) POP3 account(s)</strong> have no " +
            "PST file detected. Verify these accounts have local data " +
            "before running the Backup script."
        )
    }

    if ($Summary.Unknown -gt 0) {
        $alertsHtml += New-AlertHtml -Type 'warn' -Message (
            "&#9888;&nbsp; <strong>$($Summary.Unknown) account(s)</strong> could not be " +
            "classified automatically and require manual review. " +
            "Check the UNKNOWN entries in the account table."
        )
    }

    $alertsHtml += New-AlertHtml -Type 'info' -Message (
        "&#8505;&nbsp; Review all information below carefully before proceeding. " +
        "When satisfied, run <code>OMMigrate-01-Backup.ps1</code> to begin " +
        "the migration process."
    )

    # -- Account inventory table -------------------------------
    $accountTableHtml = New-AccountTableHtml -Accounts $Accounts `
                                             -ReportType 'Discovery'

    # -- Folder summary ----------------------------------------
    $folderSectionContent = if ($Folders -and $Folders.Count -gt 0) {
        $totalFolders = $Folders.Count
        $totalItems   = ($Folders | Measure-Object -Property ItemCount -Sum).Sum
        New-AlertHtml -Type 'info' -Message (
            "&#8505;&nbsp; <strong>$totalFolders folders</strong> enumerated across all stores " +
            "containing <strong>$totalItems total items</strong>. " +
            "Review <code>Config\folder_map.csv</code> to set Server/Local destinations after Script 01."
        )
        New-FolderSummaryHtml -Folders $Folders
    } else {
        New-AlertHtml -Type 'warn' -Message (
            "Folder enumeration was not performed in this run. " +
            "Re-run Script 00 with Outlook accessible to enumerate folders."
        )
    }

    # -- Rules inventory ---------------------------------------
    $rulesNeedingUpdate = @($Rules | Where-Object { $_.NeedsFolderUpdate })

    # -- Manually-added rules detection (audit accountability, 2026-06-27) --
    # Consolidated rules created by Invoke-BuildRulesFromMap follow a fixed
    # naming convention: "Rule: [<account>] <folder> (Part N)" (see that
    # function's $chunkName build, OMMigrate-Outlook.psm1). Administrator names his
    # own manually-added rules in short form and never uses this pattern, so
    # any rule NOT matching it is, by elimination, manually added by Administrator
    # directly in Outlook's Rules and Alerts UI -- surfaced here for audit
    # visibility only. rules_inventory.csv itself is intentionally left
    # unchanged; this classification exists only in the HTML report.
    $consolidatedNamePattern = '^Rule: \[.+\] .+ \(Part \d+\)$'
    $manuallyAddedRules = @($Rules | Where-Object { $_.RuleName -notmatch $consolidatedNamePattern })

    $rulesSectionContent = if ($Rules -and $Rules.Count -gt 0) {
        if ($rulesNeedingUpdate.Count -gt 0) {
            New-AlertHtml -Type 'warn' -Message (
                "&#9888;&nbsp; <strong>$($rulesNeedingUpdate.Count) rule(s)</strong> have folder " +
                "targets that will need updating after folder migration. " +
                "Script 03 handles this automatically -- highlighted in amber below."
            )
        }
        else {
            New-AlertHtml -Type 'ok' -Message (
                "&#10003;&nbsp; No rules have folder targets requiring updates. " +
                "Rules will continue working after migration without changes."
            )
        }

        if ($manuallyAddedRules.Count -gt 0) {
            # HTML-encode RuleName/RuleStoreName before rendering -- rule or account
            # names can legitimately contain '&', '<', '>' (e.g. "AT&T") which would
            # otherwise corrupt the HTML output. [System.Net.WebUtility]::HtmlEncode
            # is part of System.dll, always loaded, no Add-Type required.
            $manualRulesList = ($manuallyAddedRules | ForEach-Object {
                $encodedRuleName  = [System.Net.WebUtility]::HtmlEncode($_.RuleName)
                $encodedStoreName = [System.Net.WebUtility]::HtmlEncode($_.RuleStoreName)
                "<li><strong>$encodedRuleName</strong> -- $encodedStoreName</li>"
            }) -join "`n"
            New-AlertHtml -Type 'info' -Message (
                "&#128221;&nbsp; <strong>$($manuallyAddedRules.Count) manually-added rule(s)</strong> " +
                "detected this run (rules not matching the consolidated-rule naming convention). " +
                "Listed here for audit accountability only -- no action required:" +
                "<ul style='margin:6px 0 0 0'>$manualRulesList</ul>"
            )
        }

        New-RulesSummaryHtml -Rules $Rules
    } else {
        New-AlertHtml -Type 'info' -Message (
            "No Outlook Rules found in this profile, or rules enumeration " +
            "was not performed in this run."
        )
    }

    # -- Prerequisites checklist -------------------------------
    $prereqHtml = New-PrerequisiteListHtml -Accounts $Accounts

    # SendersDomain review step -- always shown when rules exist.
    # The SendersDomain column is set to a best-guess default (last
    # folder name segment) and must be reviewed before Script 03.
    $sendersDomainPrereqHtml = ''
    if ($Rules -and $Rules.Count -gt 0) {
        $sendersDomainPrereqHtml = @"
<div style='margin-bottom:16px'>
  <div style='font-weight:600;color:var(--text);margin-bottom:6px'>
    &#128394;&nbsp; Review SendersDomain column in rules_inventory.csv
  </div>
  <ul style='color:var(--text-muted);font-size:13px;padding-left:20px;margin:0'>
    <li style='margin-bottom:6px'>Open <code>Config\rules_inventory_&lt;Profile&gt;.csv</code> in Excel</li>
    <li style='margin-bottom:6px'>Review the <strong>SendersDomain</strong> column for every rule.</li>
    <li style='margin-bottom:6px'><strong>How the condition works:</strong> Outlook's <em>sender's address contains</em> condition performs a case-insensitive substring match against the sender's full email address. If the text you enter appears anywhere in the sender's address, the rule fires and routes the email to the target folder.</li>
    <li style='margin-bottom:6px'><strong>Examples:</strong>
      <ul style='margin-top:6px;padding-left:20px'>
        <li style='margin-bottom:6px'><code>example</code> &rarr; matches <code>info@example.com</code>, <code>info@example.net</code>, <code>info@example.org</code>, and any other address containing the word &ldquo;example&rdquo; &mdash; use this when you want to catch a sender across all top-level domains</li>
        <li style='margin-bottom:6px'><code>example.com</code> &rarr; matches only senders from <code>example.com</code> &mdash; use this when you want to restrict matching to one specific domain</li>
        <li style='margin-bottom:6px'><code>example.net</code> &rarr; matches only senders from <code>example.net</code> &mdash; use a specific TLD when the same name exists on multiple domains that should route to different folders</li>
      </ul>
    </li>
    <li style='margin-bottom:6px'>The current values are <strong>best-guess defaults</strong> (last folder name segment) and may need correction. Values are stored in lowercase.</li>
    <li style='margin-bottom:6px'>Correct any wrong values before running Script 03 &mdash; rules will not fire correctly until this column is verified</li>
  </ul>
</div>
"@
    }

    $prereqSectionContent = if ($prereqHtml -or $sendersDomainPrereqHtml) {
        New-AlertHtml -Type 'warn' -Message (
            "&#9888;&nbsp; The accounts below require manual steps BEFORE running Script 01. " +
            "Complete all items for each account and check them off before proceeding."
        )
        $prereqHtml
        $sendersDomainPrereqHtml
    } else {
        New-AlertHtml -Type 'ok' -Message (
            "&#10003;&nbsp; No special prerequisites required. " +
            "All accounts can be migrated without pre-work."
        )
    }

    # -- Action plan -------------------------------------------
    $actionPlanHtml = @"
<table>
  <thead>
    <tr><th>Script</th><th>Name</th><th>Action</th><th>Accounts</th><th>Safe to Re-run</th></tr>
  </thead>
  <tbody>
    <tr>
      <td><code>Script 00</code></td>
      <td>Discover</td>
      <td>Registry scan, account classification, CSV generation</td>
      <td>All $($Summary.Total)</td>
      <td><span class='status-ok'>&#10003; Yes -- read only</span></td>
    </tr>
    <tr>
      <td><code>Script 01</code></td>
      <td>Backup</td>
      <td>Export and verify PST backups for all POP3 accounts</td>
      <td>$($Summary.ToMigrate) POP3</td>
      <td><span class='status-ok'>&#10003; Yes -- non-destructive</span></td>
    </tr>
    <tr>
      <td><code>Script 02</code></td>
      <td>Convert</td>
      <td>Remove POP3 accounts, add IMAP accounts</td>
      <td>$($Summary.ToMigrate) POP3</td>
      <td><span class='status-warn'>&#9888; Partial -- uses checkpoint</span></td>
    </tr>
    <tr>
      <td><code>Script 03</code></td>
      <td>Restore</td>
      <td>Migrate folders, copy email, update rules</td>
      <td>All with local folders</td>
      <td><span class='status-warn'>&#9888; Partial -- uses checkpoint</span></td>
    </tr>
  </tbody>
</table>
"@

    # -- Assemble full report ----------------------------------
    $html  = Get-HtmlReportHeader `
                 -Title    'Discovery Report' `
                 -Subtitle "Pre-Migration Account Inventory -- Profile: $ProfileName"

    $html += $statGridHtml
    $html += Get-HtmlReportSection -Title 'Pre-Flight Notices' -Content ([string]$alertsHtml)
    $html += Get-HtmlReportSection -Title 'Account Inventory'  -Content ([string]$accountTableHtml)
    $html += Get-HtmlReportSection -Title 'Folder Tree Summary' -Content ([string]($folderSectionContent -join ""))
    $html += Get-HtmlReportSection -Title 'Outlook Rules Inventory' -Content ([string]($rulesSectionContent -join ""))
    $html += Get-HtmlReportSection -Title 'Prerequisites -- Manual Steps Required' `
                                   -Content ([string]$prereqSectionContent)
    $html += Get-HtmlReportSection -Title 'Migration Action Plan' -Content ([string]$actionPlanHtml)
    $html += Get-HtmlReportFooter

    # -- Write file --------------------------------------------
    if (-not $Global:OMMigrate.WhatIf) {
        try {
            # Fixed 2026-06-18: PowerShell 5.1's `Set-Content -Encoding UTF8` always
            # prepends a UTF-8 BOM (byte order mark) -- there is no UTF8NoBOM option
            # in 5.1 (that was added in PowerShell 6+). The BOM is harmless for browser
            # rendering but pollutes the file for any downstream tool that diffs,
            # greps, or parses the HTML. Writing directly via .NET's UTF8Encoding with
            # the BOM flag explicitly set to $false avoids it while staying PS 5.1-safe.
            [System.IO.File]::WriteAllText($reportFile, $html, (New-Object System.Text.UTF8Encoding $false))
            Write-OMMigrateLog -Message "Discovery Report written: $reportFile" -Level INFO
            Write-AuditEntry  -Action 'REPORT_DISCOVERY_WRITTEN' `
                              -Detail "Path=$reportFile"
        }
        catch {
            Write-OMMigrateLog -Message "Failed to write Discovery Report: $_" -Level ERROR
            throw
        }
    }
    else {
        Write-OMMigrateLog -Message "WhatIf: Would write Discovery Report to $reportFile" `
                           -Level INFO -WhatIfPrefix
    }

    return $reportFile
}


# ============================================================
#  REGION: BACKUP REPORT (Script 01)
# ============================================================

function New-BackupReport {
    <#
    .SYNOPSIS
        Generates the Backup verification HTML report from Script 01.

    .DESCRIPTION
        Documents the PST backup operation for every POP3 account --
        source file, backup destination, size, and verification status.
        This report serves as the paper trail confirming backups exist
        before any account is removed or modified.

        The report is the gate document -- Script 02 will not proceed
        without a successful backup manifest, and this report gives
        the operator the human-readable version of that manifest.

    .PARAMETER Accounts
        Array of account objects with backup results populated:
            BackupStatus        SUCCESS | FAILED | SKIPPED
            BackupPath          Full path to backup PST file
            BackupSizeFormatted Human-readable backup size
            BackupDetail        Additional detail or error message

    .PARAMETER TotalSizeFormatted
        Human-readable total size of all backups combined.

    .PARAMETER BackupFolder
        Path to the folder where backups were written.

    .OUTPUTS
        [string] -- Path to the generated HTML report file.

    .EXAMPLE
        $reportPath = New-BackupReport `
            -Accounts           $accounts `
            -TotalSizeFormatted '4.2 GB' `
            -BackupFolder       'C:\Migration\Backups'
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [array]$Accounts,

        [Parameter(Mandatory = $false)]
        [string]$TotalSizeFormatted = '',

        [Parameter(Mandatory = $false)]
        [string]$BackupFolder = ''
    )

    Write-OMMigrateLog -Message 'Generating Backup Report...' -Level INFO

    $reportFile = Get-ReportFilePath -ReportName 'Backup'

    # -- Compute summary counts --------------------------------
    $succeeded = @($Accounts | Where-Object { $_.BackupStatus -eq 'SUCCESS'  }).Count
    $failed    = @($Accounts | Where-Object { $_.BackupStatus -eq 'FAILED'   }).Count
    $skipped   = @($Accounts | Where-Object { $_.BackupStatus -eq 'SKIPPED'  }).Count
    $total     = $Accounts.Count

    $overallStatus = if ($failed -gt 0) { 'FAILED' }
                     elseif ($succeeded -eq ($total - $skipped)) { 'SUCCESS' }
                     else { 'WARNING' }

    # -- Stat grid ---------------------------------------------
    $stats = [ordered]@{
        'Accounts Backed Up'  = $succeeded
        'Backup Failed'       = $failed
        'Skipped'             = $skipped
        'Total Backup Size'   = if ($TotalSizeFormatted) { $TotalSizeFormatted } else { 'N/A' }
    }
    $statGridHtml = Get-HtmlStatGrid -Stats $stats

    # -- Alerts ------------------------------------------------
    $alertsHtml = ''

    if ($overallStatus -eq 'SUCCESS') {
        $alertsHtml += New-AlertHtml -Type 'ok' -Message (
            "&#10003;&nbsp; All $succeeded PST backups completed and verified successfully. " +
            "You may now proceed to run <code>OMMigrate-02-Convert.ps1</code>."
        )
    }
    elseif ($overallStatus -eq 'FAILED') {
        $alertsHtml += New-AlertHtml -Type 'warn' -Message (
            "&#10007;&nbsp; <strong>$failed backup(s) FAILED</strong>. " +
            "Do NOT proceed to Script 02 until all backups are verified. " +
            "Resolve the failures shown below and re-run Script 01."
        )
    }
    else {
        $alertsHtml += New-AlertHtml -Type 'warn' -Message (
            "&#9888;&nbsp; Backup completed with warnings. " +
            "Review the table below before proceeding to Script 02."
        )
    }

    if ($BackupFolder) {
        $alertsHtml += New-AlertHtml -Type 'info' -Message (
            "&#8505;&nbsp; Backup files are stored in: <code>$BackupFolder</code>. " +
            "Do not move or rename these files -- Script 02 uses their exact paths."
        )
    }

    # -- Account backup table ----------------------------------
    $backupTableHtml = New-AccountTableHtml -Accounts $Accounts `
                                            -ReportType 'Backup'

    # -- Assemble report ---------------------------------------
    $html  = Get-HtmlReportHeader `
                 -Title    'Backup Verification Report' `
                 -Subtitle 'PST Export and Verification Results -- Script 01'

    $html += $statGridHtml
    $html += Get-HtmlReportSection -Title 'Backup Status'   -Content $alertsHtml
    $html += Get-HtmlReportSection -Title 'Backup Details'  -Content $backupTableHtml
    $html += Get-HtmlReportFooter

    if (-not $Global:OMMigrate.WhatIf) {
        try {
            # Fixed 2026-06-18: PowerShell 5.1's `Set-Content -Encoding UTF8` always
            # prepends a UTF-8 BOM (byte order mark) -- there is no UTF8NoBOM option
            # in 5.1 (that was added in PowerShell 6+). The BOM is harmless for browser
            # rendering but pollutes the file for any downstream tool that diffs,
            # greps, or parses the HTML. Writing directly via .NET's UTF8Encoding with
            # the BOM flag explicitly set to $false avoids it while staying PS 5.1-safe.
            [System.IO.File]::WriteAllText($reportFile, $html, (New-Object System.Text.UTF8Encoding $false))
            Write-OMMigrateLog -Message "Backup Report written: $reportFile" -Level INFO
            Write-AuditEntry  -Action 'REPORT_BACKUP_WRITTEN' `
                              -Detail "Path=$reportFile | Status=$overallStatus"
        }
        catch {
            Write-OMMigrateLog -Message "Failed to write Backup Report: $_" -Level ERROR
            throw
        }
    }
    else {
        Write-OMMigrateLog -Message "WhatIf: Would write Backup Report to $reportFile" `
                           -Level INFO -WhatIfPrefix
    }

    return $reportFile
}


# ============================================================
#  REGION: MIGRATION REPORT (Script 02)
# ============================================================

function New-MigrationReport {
    <#
    .SYNOPSIS
        Generates the Migration HTML report from Script 02 results.

    .DESCRIPTION
        Documents the account conversion operation -- which accounts
        had POP3 removed, which had IMAP added, connection verification
        results, and which accounts were skipped.

        Color-coded per account: green = migrated, amber = skipped,
        red = failed. Designed to serve as a client deliverable
        for IT consultants.

    .PARAMETER Accounts
        Array of account objects with migration results populated:
            MigrationAction     MIGRATE | SKIP | FOLDER-ONLY | MANUAL
            MigrationOutcome    SUCCESS | FAILED | SKIPPED | WARNING
            MigrationDetail     Additional context or error message
            NewImapServer       IMAP server hostname used
            NewImapPort         IMAP port used

    .OUTPUTS
        [string] -- Path to the generated HTML report file.

    .EXAMPLE
        $reportPath = New-MigrationReport -Accounts $accounts
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [array]$Accounts = @(),

        [Parameter(Mandatory = $false)]
        [int]$RulesUpdated = 0,

        [Parameter(Mandatory = $false)]
        [int]$RulesDisabled = 0,

        [Parameter(Mandatory = $false)]
        [string]$DisabledRulesCsvPath = '',

        [Parameter(Mandatory = $false)]
        [string]$Subtitle = 'Account Protocol Conversion Results -- Script 02',

        [Parameter(Mandatory = $false)]
        [string]$ReportName = 'Migration',

        [Parameter(Mandatory = $false)]
        [PSCustomObject]$ArtifactTotals = $null,

        # -- Additive rules-reporting parameters (Script 03 report enrichment) --
        # All default to "no data supplied" so existing callers (Script 02, Script 04)
        # are completely unaffected. Populated by Script 03 with its rollup counters.
        [Parameter(Mandatory = $false)]
        [int]$RulesSkipped = 0,

        [Parameter(Mandatory = $false)]
        [int]$RulesNoChange = 0,

        [Parameter(Mandatory = $false)]
        [int]$RulesStopProcessingSet = 0,

        [Parameter(Mandatory = $false)]
        [int]$RulesStopProcessingFailed = 0,

        # Default store (ameritech) "not processed this pass" count -- NOT a
        # failure. The default store loads rules via .rwz import (preserves
        # StopProcessing natively) and never goes through Create()-based
        # purge/recreate. This only reflects the COM Item() ceiling silently
        # preventing folder-target remap/sort from running for it this run.
        [Parameter(Mandatory = $false)]
        [int]$RulesDefaultStoreNotProcessed = 0,

        [Parameter(Mandatory = $false)]
        [array]$RulesStoreSummary = @()
    )

    Write-OMMigrateLog -Message 'Generating Migration Report...' -Level INFO

    $reportFile = Get-ReportFilePath -ReportName $ReportName

    # -- Compute summary counts --------------------------------
    $migrated  = @($Accounts | Where-Object { $_.MigrationOutcome -eq 'SUCCESS'  }).Count
    $failed    = @($Accounts | Where-Object { $_.MigrationOutcome -eq 'FAILED'   }).Count
    $skipped   = @($Accounts | Where-Object { $_.MigrationOutcome -eq 'SKIPPED'  }).Count
    $warned    = @($Accounts | Where-Object { $_.MigrationOutcome -eq 'WARNING'  }).Count
    $total     = $Accounts.Count

    $overallStatus = if ($failed -gt 0) { 'FAILED' }
                     elseif ($warned -gt 0) { 'WARNING' }
                     elseif ($migrated -gt 0) { 'SUCCESS' }
                     elseif ($failed -eq 0 -and $warned -eq 0) { 'SUCCESS' }  # All skipped cleanly -- no failures
                     else { 'WARNING' }

    # -- Stat grid ---------------------------------------------
    # When running rules-only (-SkipFolderMigration), $Accounts is empty and
    # folder migration counts are all zero. Show rules stats instead so the
    # report has meaningful data regardless of which phases ran this session.
    $stats = if ($ArtifactTotals) {
        # Script 04 artifacts run -- show artifact counts instead of migration counts
        [ordered]@{
            'Calendar Copied' = $ArtifactTotals.Calendar
            'Contacts Copied'           = $ArtifactTotals.Contacts
            'Contact Subfolders Copied' = $ArtifactTotals.ContactSubfolders
            'Tasks Copied'    = $ArtifactTotals.Tasks
            'Notes Copied'    = $ArtifactTotals.Notes
            'Journal Copied'  = $ArtifactTotals.Journal
        }
    } elseif ($total -eq 0 -and ($RulesUpdated -gt 0 -or $RulesDisabled -gt 0)) {
        # Script 03 rules-only run -- show rules counts
        [ordered]@{
            'Rules Updated'  = $RulesUpdated
            'Rules Disabled' = $RulesDisabled
            'Accounts'       = 0
            'Warnings'       = if ($RulesDisabled -gt 0) { $RulesDisabled } else { 0 }
        }
    } else {
        # Script 02 migration run -- show standard migration counts
        [ordered]@{
            'Migrated to IMAP'   = $migrated
            'Migration Failed'   = $failed
            'Skipped / No Change'= $skipped
            'Warnings'           = $warned
        }
    }
    $statGridHtml = Get-HtmlStatGrid -Stats $stats

    # -- Additive: Rules Processing stat grid -------------------
    # Rendered as its OWN section, independent of which branch above fired,
    # so the same rules detail appears whether this report came from a
    # folder-migration run, a -RefreshRulesOnly run, or a -RecreateRules run.
    # Only rendered when there is actually rules data to show.
    $rulesStatGridHtml = ''
    $hasRulesReportingData = (
        $RulesUpdated -gt 0 -or $RulesDisabled -gt 0 -or $RulesSkipped -gt 0 -or
        $RulesNoChange -gt 0 -or $RulesStopProcessingSet -gt 0 -or $RulesStopProcessingFailed -gt 0 -or
        $RulesDefaultStoreNotProcessed -gt 0
    )
    if ($hasRulesReportingData) {
        $rulesStats = [ordered]@{
            'Rules Updated'              = $RulesUpdated
            'Rules Skipped'              = $RulesSkipped
            'Rules No Change'            = $RulesNoChange
            'Rules Disabled'             = $RulesDisabled
            'StopProcessing Set'         = $RulesStopProcessingSet
            'StopProcessing Needs Manual Fix' = $RulesStopProcessingFailed
            'Primary Store Rules Not Processed This Run' = $RulesDefaultStoreNotProcessed
        }
        $rulesStatGridHtml = Get-HtmlStatGrid -Stats $rulesStats
    }

    # -- Alerts ------------------------------------------------
    $alertsHtml = ''

    if ($ArtifactTotals) {
        # Script 04 artifacts run -- show artifact-specific messages
        $totalCopied  = $ArtifactTotals.Calendar + $ArtifactTotals.Contacts +
                        $ArtifactTotals.ContactSubfolders +
                        $ArtifactTotals.Tasks + $ArtifactTotals.Notes + $ArtifactTotals.Journal
        $totalFailed  = @($Accounts | Where-Object { $_.MigrationOutcome -eq 'FAILED'  }).Count
        $totalWarned  = @($Accounts | Where-Object { $_.MigrationOutcome -eq 'WARNING' }).Count
        $totalSkipped = @($Accounts | Where-Object { $_.MigrationOutcome -eq 'SKIPPED' }).Count

        if ($overallStatus -eq 'SUCCESS') {
            if ($totalCopied -gt 0) {
                $alertsHtml += New-AlertHtml -Type 'ok' -Message (
                    "&#10003;&nbsp; Artifact migration completed successfully. " +
                    "<strong>$totalCopied item(s)</strong> copied to IMAP stores. " +
                    "Items should sync to your devices within minutes."
                )
            }
            else {
                $alertsHtml += New-AlertHtml -Type 'ok' -Message (
                    "&#10003;&nbsp; Artifact migration completed successfully. " +
                    "No new items to copy -- all artifacts already present in IMAP stores, " +
                    "or backup PSTs contained no artifact folders."
                )
            }
        }
        elseif ($overallStatus -eq 'FAILED') {
            $alertsHtml += New-AlertHtml -Type 'warn' -Message (
                "&#10007;&nbsp; Artifact migration failed for one or more accounts. " +
                "Review the account table below. Re-running is safe -- only missing items will be copied."
            )
        }
        else {
            $alertsHtml += New-AlertHtml -Type 'warn' -Message (
                "&#9888;&nbsp; Artifact migration completed with warnings. " +
                "Review the account table below for details."
            )
        }
        if ($totalSkipped -gt 0) {
            $alertsHtml += New-AlertHtml -Type 'info' -Message (
                "&#8505;&nbsp; <strong>$totalSkipped account(s)</strong> were skipped -- " +
                "either no backup PST was found or migration was skipped by operator."
            )
        }
    }
    elseif ($overallStatus -eq 'SUCCESS') {
        # When rules ran, show rules-aware success message instead of the
        # generic account migration message -- this report may be from Script 03.
        if ($RulesUpdated -gt 0 -or $RulesDisabled -gt 0) {
            $totalRules = $RulesUpdated + $RulesDisabled
            if ($RulesDisabled -gt 0) {
                $alertsHtml += New-AlertHtml -Type 'warn' -Message (
                    "&#9888;&nbsp; <strong>$RulesUpdated of $totalRules rule(s)</strong> successfully remapped. " +
                    "<strong>$RulesDisabled rule(s)</strong> could not be resolved and were disabled. " +
                    "Fix the folder paths in <code>rules_inventory_Outlook.csv</code> and re-run Script 03."
                )
            }
            else {
                $alertsHtml += New-AlertHtml -Type 'ok' -Message (
                    "&#10003;&nbsp; <strong>$RulesUpdated of $totalRules rule(s)</strong> successfully remapped. " +
                    "All rules resolved -- no disabled rules. " +
                    "You may now verify Outlook Rules are routing email correctly."
                )
            }
        }
        elseif ($RulesSkipped -gt 0) {
            # No rules were created or disabled, but some were skipped -- this is
            # the idempotency Match case (Memory #16): rules already match the CSV
            # from a prior run, so purge/recreate was skipped to preserve any
            # manually-set StopProcessing. This is a confirmation, not a no-op.
            $alertsHtml += New-AlertHtml -Type 'ok' -Message (
                "&#10003;&nbsp; <strong>$RulesSkipped rule(s)</strong> already match " +
                "<code>rules_inventory_Outlook.csv</code> -- no changes needed. " +
                "Purge/recreate was skipped to preserve any manually-set StopProcessing conditions."
            )
        }
        else {
            $alertsHtml += New-AlertHtml -Type 'ok' -Message (
                "&#10003;&nbsp; All accounts migrated successfully. " +
                "You may now proceed to run <code>OMMigrate-03-Restore.ps1</code> " +
                "to migrate folder contents and update Outlook Rules."
            )
        }

        $alertsHtml += New-AlertHtml -Type 'info' -Message (
            "&#8505;&nbsp; Accounts shown as SKIPPED were already IMAP or Exchange " +
            "and required no protocol change. Their local folder structure " +
            "will still be assessed by Script 03."
        )
    }
    elseif ($overallStatus -eq 'FAILED') {
        $alertsHtml += New-AlertHtml -Type 'warn' -Message (
            "&#10007;&nbsp; <strong>$failed account(s) failed</strong> migration. " +
            "Review failures below. PST backups are intact in the Backups folder. " +
            "Resolve issues and re-run Script 02 -- completed accounts will be skipped."
        )

        $alertsHtml += New-AlertHtml -Type 'info' -Message (
            "&#8505;&nbsp; Accounts shown as SKIPPED were already IMAP or Exchange " +
            "and required no protocol change. Their local folder structure " +
            "will still be assessed by Script 03."
        )
    }
    else {
        $alertsHtml += New-AlertHtml -Type 'warn' -Message (
            "&#9888;&nbsp; Migration completed with warnings. " +
            "Review all accounts before proceeding to Script 03."
        )

        $alertsHtml += New-AlertHtml -Type 'info' -Message (
            "&#8505;&nbsp; Accounts shown as SKIPPED were already IMAP or Exchange " +
            "and required no protocol change. Their local folder structure " +
            "will still be assessed by Script 03."
        )
    }

    # -- Account results table --------------------------------
    # For Script 04 artifact runs, build a custom artifact table showing
    # per-account artifact counts. For all other runs use the standard
    # Migration table format.
    $migrationTableHtml = ''
    if ($Accounts -and $Accounts.Count -gt 0) {
        if ($ArtifactTotals) {
            # Build artifact-specific table
            $headerHtml = '<th>Email Address</th><th>Tag</th><th>Calendar</th><th>Contacts</th><th>Subfolders</th><th>Tasks</th><th>Notes</th><th>Journal</th><th>Failed</th><th>Outcome</th>'
            $rowsHtml = ''
            foreach ($acct in $Accounts) {
                $tagBadge    = New-BadgeHtml -Text $acct.ProviderTag -Type 'Tag'
                $outcome     = if ($acct.MigrationOutcome) { $acct.MigrationOutcome } else { 'PENDING' }
                $outcomeHtml = New-OutcomeHtml -Outcome $outcome

                # Parse detail string: "Cal=N Con=N Sug=N Tsk=N Not=N Jrn=N | Failed=N"
                $cal = $con = $sug = $tsk = $not = $jrn = $fail = 0
                if ($acct.MigrationDetail -match 'Cal=(\d+)') { $cal  = [int]$Matches[1] }
                if ($acct.MigrationDetail -match 'Con=(\d+)') { $con  = [int]$Matches[1] }
                if ($acct.MigrationDetail -match 'Sug=(\d+)') { $sug  = [int]$Matches[1] }
                if ($acct.MigrationDetail -match 'Tsk=(\d+)') { $tsk  = [int]$Matches[1] }
                if ($acct.MigrationDetail -match 'Not=(\d+)') { $not  = [int]$Matches[1] }
                if ($acct.MigrationDetail -match 'Jrn=(\d+)') { $jrn  = [int]$Matches[1] }
                if ($acct.MigrationDetail -match 'Failed=(\d+)') { $fail = [int]$Matches[1] }

                $failHtml = if ($fail -gt 0) {
                    "<span class='status-warn'>$fail</span>"
                } else {
                    "<span style='color:var(--text-muted)'>0</span>"
                }

                $rowsHtml += "<tr><td><strong>$($acct.EmailAddress)</strong></td><td>$tagBadge</td><td>$cal</td><td>$con</td><td>$sug</td><td>$tsk</td><td>$not</td><td>$jrn</td><td>$failHtml</td><td>$outcomeHtml</td></tr>`n"
            }

            # Totals row
            $acctTotal = @($Accounts).Count
            $tfootHtml = @"
  <tr style='background:var(--surface-2,rgba(0,0,0,0.06));font-weight:600;border-top:2px solid var(--border)'>
    <td colspan='2'><strong>Total: $acctTotal account(s)</strong></td>
    <td><strong>$($ArtifactTotals.Calendar)</strong></td>
    <td><strong>$($ArtifactTotals.Contacts)</strong></td>
    <td><strong>$($ArtifactTotals.ContactSubfolders)</strong></td>
    <td><strong>$($ArtifactTotals.Tasks)</strong></td>
    <td><strong>$($ArtifactTotals.Notes)</strong></td>
    <td><strong>$($ArtifactTotals.Journal)</strong></td>
    <td></td><td></td>
  </tr>
"@
            $migrationTableHtml = @"
<table>
  <thead><tr>$headerHtml</tr></thead>
  <tbody>
$rowsHtml  </tbody>
  <tfoot>
$tfootHtml  </tfoot>
</table>
"@
        }
        else {
            $migrationTableHtml = New-AccountTableHtml -Accounts $Accounts `
                                                       -ReportType 'Migration'
        }
    }

    # -- Rules summary section (rules-only runs) ---------------
    # When -SkipFolderMigration is used, no account results exist but rules
    # were updated. Build a dedicated Rules Summary section so the report
    # shows meaningful data instead of an empty table.
    $rulesSummarySectionHtml = ''
    if ($RulesUpdated -gt 0 -or $RulesDisabled -gt 0) {
        $rulesAlertHtml = ''
        if ($RulesUpdated -gt 0) {
            $rulesAlertHtml += New-AlertHtml -Type 'ok' -Message (
                "&#10003;&nbsp; <strong>$RulesUpdated rule(s)</strong> successfully remapped " +
                "to their new folder targets across all stores."
            )
        }
        if ($RulesDisabled -gt 0) {
            # Build clickable file:// link if CSV path was provided.
            # Chrome may block file:// links from local HTML -- falls back to
            # plain code text so the path is always visible and copy-pasteable.
            $csvLinkHtml = if ($DisabledRulesCsvPath) {
                $csvFileName = [System.IO.Path]::GetFileName($DisabledRulesCsvPath)
                $csvUri      = 'file:///' + $DisabledRulesCsvPath.Replace('\', '/')
                " &mdash; <a href='$csvUri' style='color:#e3b341'>$csvFileName</a>" +
                " <span style='font-size:11px;color:var(--text-muted)'>(click to open in Excel)</span>"
            } else { '' }
            $rulesAlertHtml += New-AlertHtml -Type 'warn' -Message (
                "&#9888;&nbsp; <strong>$RulesDisabled rule(s)</strong> were disabled because " +
                "their target folder could not be resolved. " +
                "Fix the folder paths in <code>rules_inventory_Outlook.csv</code> " +
                "and re-run Script 03.$csvLinkHtml"
            )
        }
        else {
            $rulesAlertHtml += New-AlertHtml -Type 'ok' -Message (
                "&#10003;&nbsp; All rules resolved successfully -- no disabled rules."
            )
        }
        $rulesSummarySectionHtml = $rulesAlertHtml
    }

    # -- Additive: StopProcessing manual-fix alert --------------
    # Appended to the existing rules summary section (built above, untouched)
    # whenever any rules could not have StopProcessing set via COM. This is a
    # known permanent limitation for Create()-path rules on secondary stores --
    # the admin needs to apply it manually in Outlook's Rules Manager.
    if ($RulesStopProcessingFailed -gt 0) {
        $stopProcessingAlertHtml = New-AlertHtml -Type 'warn' -Message (
            "&#9888;&nbsp; <strong>$RulesStopProcessingFailed rule(s)</strong> could not have the " +
            "StopProcessing condition added automatically. These rules will need a manual update " +
            "via the Outlook Rules Manager to add their StopProcessing condition."
        )
        $rulesSummarySectionHtml += $stopProcessingAlertHtml
    }

    # -- Additive: primary store "not processed this run" info alert --------
    # Deliberately Type 'info', NOT 'warn' -- this is not a failure. The
    # primary/default store's rules are loaded via .rwz import and natively
    # retain StopProcessing; they never go through Create()-based purge/
    # recreate at all. This only reflects the COM Item() ceiling preventing
    # folder-target remap/sort from running for the primary store this pass.
    if ($RulesDefaultStoreNotProcessed -gt 0) {
        $defaultStoreInfoAlertHtml = New-AlertHtml -Type 'info' -Message (
            "&#8505;&nbsp; The primary store's rules were not processed this run -- " +
            "this store has too many rules for Outlook's COM Item() access to enumerate " +
            "at this rule count. This is a known, permanent characteristic of this store " +
            "size, not an error. Primary store rules retain their StopProcessing condition " +
            "via the original <code>.rwz</code> import and are unaffected by this. If a " +
            "folder target or sort order needs to change here, use Outlook's Rules and " +
            "Alerts UI directly."
        )
        $rulesSummarySectionHtml += $defaultStoreInfoAlertHtml
    }

    # -- Additive: Rules Processing Detail table (per-store) ----
    # Built from $RulesStoreSummary (one row per store/account processed by
    # Script 03's rules-update code paths). Shown only when data is supplied --
    # other callers (Script 02, Script 04) leave this empty by default.
    $rulesStoreSummaryTableHtml = ''
    if ($RulesStoreSummary -and @($RulesStoreSummary).Count -gt 0) {
        $rulesStoreSummaryTableHtml = New-RulesStoreSummaryHtml -StoreSummary $RulesStoreSummary
    }

    # -- Assemble report ---------------------------------------
    $html  = Get-HtmlReportHeader `
                 -Title    'Migration Report' `
                 -Subtitle $Subtitle

    $html += $statGridHtml
    if ($rulesStatGridHtml) {
        $html += Get-HtmlReportSection -Title 'Rules Processing Summary' -Content $rulesStatGridHtml
    }
    $html += Get-HtmlReportSection -Title 'Migration Status'  -Content $alertsHtml
    if ($rulesSummarySectionHtml) {
        $html += Get-HtmlReportSection -Title 'Rules Update Summary' -Content $rulesSummarySectionHtml
    }
    if ($rulesStoreSummaryTableHtml) {
        $html += Get-HtmlReportSection -Title 'Rules Processing Detail (by Store/Account)' -Content $rulesStoreSummaryTableHtml
    }
    if ($migrationTableHtml) {
        $html += Get-HtmlReportSection -Title 'Account Results' -Content $migrationTableHtml
    }

    $html += Get-HtmlReportFooter

    if (-not $Global:OMMigrate.WhatIf) {
        try {
            # Fixed 2026-06-18: PowerShell 5.1's `Set-Content -Encoding UTF8` always
            # prepends a UTF-8 BOM (byte order mark) -- there is no UTF8NoBOM option
            # in 5.1 (that was added in PowerShell 6+). The BOM is harmless for browser
            # rendering but pollutes the file for any downstream tool that diffs,
            # greps, or parses the HTML. Writing directly via .NET's UTF8Encoding with
            # the BOM flag explicitly set to $false avoids it while staying PS 5.1-safe.
            [System.IO.File]::WriteAllText($reportFile, $html, (New-Object System.Text.UTF8Encoding $false))
            Write-OMMigrateLog -Message "Migration Report written: $reportFile" -Level INFO
            Write-AuditEntry  -Action 'REPORT_MIGRATION_WRITTEN' `
                              -Detail "Path=$reportFile | Status=$overallStatus"
        }
        catch {
            Write-OMMigrateLog -Message "Failed to write Migration Report: $_" -Level ERROR
            throw
        }
    }
    else {
        Write-OMMigrateLog -Message "WhatIf: Would write Migration Report to $reportFile" `
                           -Level INFO -WhatIfPrefix
    }

    return $reportFile
}


# ============================================================
#  REGION: ROLLBACK REPORT (On Demand / On Failure)
# ============================================================

function New-RollbackReport {
    <#
    .SYNOPSIS
        Generates a Rollback HTML report when a migration fails or
        is interrupted in a way that requires operator intervention.

    .DESCRIPTION
        Documents the state of each account at the time of failure --
        what completed, what failed, what was never reached -- and
        provides per-account recovery notes.

        This report is generated automatically when:
            - Script 02 exits with FAILED status
            - The operator requests a rollback assessment
            - An emergency exit occurs during Script 02

        The report does NOT perform rollback itself -- it documents
        what the operator needs to do manually and what the scripts
        can handle automatically on resume.

    .PARAMETER Accounts
        Array of account objects with rollback state populated:
            LastCompletedStep   Last successful operation
            RollbackOutcome     SUCCESS | FAILED | PENDING
            RecoveryNote        What the operator needs to do

    .PARAMETER InterruptedAt
        Email address of the account being processed at interruption.

    .PARAMETER Reason
        Description of why the rollback report is being generated.

    .OUTPUTS
        [string] -- Path to the generated HTML report file.

    .EXAMPLE
        $reportPath = New-RollbackReport `
            -Accounts       $accounts `
            -InterruptedAt  'user@domain.com' `
            -Reason         'Script 02 interrupted by operator Ctrl+C'
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [array]$Accounts,

        [Parameter(Mandatory = $false)]
        [string]$InterruptedAt = '',

        [Parameter(Mandatory = $false)]
        [string]$Reason = 'Migration interrupted or failed'
    )

    Write-OMMigrateLog -Message 'Generating Rollback Report...' -Level INFO

    $reportFile = Get-ReportFilePath -ReportName 'Rollback'

    # -- Counts ------------------------------------------------
    $completed = @($Accounts | Where-Object { $_.RollbackOutcome -eq 'SUCCESS' }).Count
    $failed    = @($Accounts | Where-Object { $_.RollbackOutcome -eq 'FAILED'  }).Count
    $pending   = @($Accounts | Where-Object { $_.RollbackOutcome -eq 'PENDING' -or
                                              -not $_.RollbackOutcome           }).Count

    # -- Stat grid ---------------------------------------------
    $stats = [ordered]@{
        'Completed Before Exit' = $completed
        'Failed'                = $failed
        'Not Yet Processed'     = $pending
    }
    $statGridHtml = Get-HtmlStatGrid -Stats $stats

    # -- Alerts ------------------------------------------------
    $alertsHtml = New-AlertHtml -Type 'warn' -Message (
        "&#9888;&nbsp; <strong>Reason:</strong> $Reason"
    )

    if ($InterruptedAt) {
        $alertsHtml += New-AlertHtml -Type 'warn' -Message (
            "&#9888;&nbsp; Script was processing <strong>$InterruptedAt</strong> " +
            "when interrupted. Verify this account manually in Outlook before resuming."
        )
    }

    $alertsHtml += New-AlertHtml -Type 'info' -Message (
        "&#8505;&nbsp; PST backups are intact in the Backups folder. " +
        "No email data has been lost. " +
        "Accounts listed as completed do not need to be re-processed -- " +
        "re-running Script 02 will skip them automatically via checkpoint."
    )

    # -- Rollback table ----------------------------------------
    $rollbackTableHtml = New-AccountTableHtml -Accounts $Accounts `
                                              -ReportType 'Rollback'

    # -- Recovery steps ----------------------------------------
    $recoveryHtml = @"
<ol style='color:var(--text-muted);font-size:13px;line-height:2'>
  <li>Open <strong>Task Manager</strong> and confirm <code>OUTLOOK.EXE</code> is not running.</li>
  <li>Open Outlook manually and verify account list matches expectations.</li>
  <li>Check <code>RECOVERY.txt</code> in your migration working folder for details.</li>
  <li>Review the account table above -- note which accounts are PENDING.</li>
  <li>When ready, re-run <code>OMMigrate-02-Convert.ps1</code>.</li>
  <li>The script will detect the checkpoint and skip completed accounts automatically.</li>
  <li>If you need to start fully fresh, delete <code>Manifests\Step02_Checkpoint.json</code> first.</li>
</ol>
"@

    # -- Assemble report ---------------------------------------
    $html  = Get-HtmlReportHeader `
                 -Title    'Rollback Report' `
                 -Subtitle 'Migration Interruption Assessment and Recovery Guide'

    $html += $statGridHtml
    $html += Get-HtmlReportSection -Title 'What Happened'      -Content $alertsHtml
    $html += Get-HtmlReportSection -Title 'Account Status'     -Content $rollbackTableHtml
    $html += Get-HtmlReportSection -Title 'Recovery Steps'     -Content $recoveryHtml
    $html += Get-HtmlReportFooter

    if (-not $Global:OMMigrate.WhatIf) {
        try {
            # Fixed 2026-06-18: PowerShell 5.1's `Set-Content -Encoding UTF8` always
            # prepends a UTF-8 BOM (byte order mark) -- there is no UTF8NoBOM option
            # in 5.1 (that was added in PowerShell 6+). The BOM is harmless for browser
            # rendering but pollutes the file for any downstream tool that diffs,
            # greps, or parses the HTML. Writing directly via .NET's UTF8Encoding with
            # the BOM flag explicitly set to $false avoids it while staying PS 5.1-safe.
            [System.IO.File]::WriteAllText($reportFile, $html, (New-Object System.Text.UTF8Encoding $false))
            Write-OMMigrateLog -Message "Rollback Report written: $reportFile" -Level INFO
            Write-AuditEntry  -Action 'REPORT_ROLLBACK_WRITTEN' `
                              -Detail "Path=$reportFile | Reason=$Reason"
        }
        catch {
            Write-OMMigrateLog -Message "Failed to write Rollback Report: $_" -Level ERROR
        }
    }
    else {
        Write-OMMigrateLog -Message "WhatIf: Would write Rollback Report to $reportFile" `
                           -Level INFO -WhatIfPrefix
    }

    return $reportFile
}


# ============================================================
#  REGION: MODULE EXPORTS
# ============================================================

Export-ModuleMember -Function @(

    # Shared helpers
    'Get-ReportFilePath'
    'New-BadgeHtml'
    'New-OutcomeHtml'
    'New-AlertHtml'
    'New-AccountTableHtml'
    'New-FolderSummaryHtml'
    'New-RulesSummaryHtml'
    'New-RulesStoreSummaryHtml'
    'New-PrerequisiteListHtml'

    # Report generators
    'New-DiscoveryReport'
    'New-BackupReport'
    'New-MigrationReport'
    'New-RollbackReport'
)

# ***** END OF FILE *****
