#Requires -Version 5.1
<#
.SYNOPSIS
    OMMigrate-RemoveDuplicateRules.ps1 -- Removes duplicate Outlook rules.

.DESCRIPTION
    Reads DuplicateRules_<Profile>.csv generated by OMMigrate-FindDuplicateRules.ps1
    and removes each listed rule from Outlook via COM.

    For each group of rules sharing the same base name, keeps the highest-scoring
    copy (valid MoveToFolder target wins) and deletes the rest.

    One Save() per store after all deletions -- consistent with the OMMigrate
    atomic save pattern confirmed by Gemini.

    Run OMMigrate-FindDuplicateRules.ps1 first to generate and review the CSV.

    Standalone utility -- does NOT read or write OMMigrate_Settings.json.
    Supports multiple Outlook profiles via the -ProfileName parameter, or an
    interactive prompt if omitted: real profiles are enumerated live from
    the registry via Get-OutlookProfiles (same function Script 00 uses) --
    one found is used automatically, multiple prompts you to pick one, zero
    is an error.

.PARAMETER ProfileName
    Target a specific Outlook profile by name. If omitted, you will be
    prompted -- unless exactly one Outlook profile exists on this machine,
    in which case it is used automatically.

.PARAMETER BasePath
    Override the default working directory.
    Default: $env:USERPROFILE\Documents\OutlookMigration

.PARAMETER LogLevel
    Logging verbosity. DEBUG | INFO | WARN | ERROR. Default: INFO

.PARAMETER WhatIf
    Preview mode -- shows what would be deleted without making any changes.

.EXAMPLE
    .\OMMigrate-RemoveDuplicateRules.ps1 -WhatIf
    .\OMMigrate-RemoveDuplicateRules.ps1
    .\OMMigrate-RemoveDuplicateRules.ps1 -ProfileName "Outlook"
.NOTES
    -------------------------------------------------------------------------
    OutlookMailMigrator (OMMigrate)
    -------------------------------------------------------------------------
    Originator & Architect:    Kirk Shallcross - Shallcross Consulting
    Implementation Specialist: Anthropic Claude AI
    Inception Date:            May 2026
    Version:                   1.5.2
    -------------------------------------------------------------------------
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$ProfileName = '',

    [Parameter(Mandatory = $false)]
    [string]$BasePath = '',

    [Parameter(Mandatory = $false)]
    [ValidateSet('DEBUG','INFO','WARN','ERROR')]
    [string]$LogLevel = 'INFO',

    [Parameter(Mandatory = $false)]
    [switch]$WhatIf
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8


# ============================================================
#  REGION: MODULE IMPORT
# ============================================================

# Utilities\ is a sibling of Modules\ (both directly under Documents\OMMigrate\),
# not nested inside it like Scripts\ scripts might assume -- go up one level.
$Script:ModulesPath = Join-Path $PSScriptRoot '..\Modules'

if (-not (Test-Path $Script:ModulesPath)) {
    Write-Error "OMMigrate Modules folder not found at: $Script:ModulesPath"
    exit 1
}

foreach ($moduleName in @('OMMigrate-Core','OMMigrate-Registry',
                           'OMMigrate-Outlook','OMMigrate-Reporting')) {
    $modulePath = Join-Path $Script:ModulesPath "$moduleName.psm1"
    if (-not (Test-Path $modulePath)) {
        Write-Error "Required module not found: $modulePath"
        exit 1
    }
    try {
        Import-Module $modulePath -Force -DisableNameChecking -ErrorAction Stop
    }
    catch {
        Write-Error "Failed to import $moduleName : $_"
        exit 1
    }
}


# ============================================================
#  REGION: SESSION INITIALIZATION
# ============================================================

Initialize-OMMigrate `
    -ScriptName 'OMMigrate-RemoveDuplicateRules' `
    -BasePath   $BasePath `
    -LogLevel   $LogLevel `
    -IsWhatIf   $WhatIf.IsPresent `
    -Sanitize   $false

Register-ExitHandlers -ScriptStep 0
Show-ExitBanner


# ============================================================
#  REGION: MAIN
# ============================================================

Write-Host ''
Write-Host '  OMMigrate-RemoveDuplicateRules' -ForegroundColor Cyan
if ($WhatIf) {
    Write-Host '  [PREVIEW MODE] No changes will be made.' -ForegroundColor Yellow
}
Write-Host ''

# -- Resolve Outlook profile ---------------------------------------------------
# Standalone utility -- never reads or writes OMMigrate_Settings.json. Real
# profiles are enumerated live from the registry via Get-OutlookProfiles
# (same function Script 00 uses) -- never inferred from leftover files.
# Resolved before locating the CSV below since the report filename itself
# is profile-suffixed.
$foundProfiles = @(Get-OutlookProfiles)

if ([string]::IsNullOrWhiteSpace($ProfileName)) {
    if ($foundProfiles.Count -eq 1) {
        # Exactly one Outlook profile on this machine -- use it automatically.
        $ProfileName = $foundProfiles[0].Name
    }
    elseif ($foundProfiles.Count -gt 1) {
        # Multiple profiles found -- must ask, no way to safely guess.
        Write-Host '  Multiple Outlook profiles found on this machine:' -ForegroundColor Yellow
        foreach ($p in $foundProfiles) {
            $defaultTag = if ($p.IsDefault) { ' (default)' } else { '' }
            Write-Host "    - $($p.Name)$defaultTag" -ForegroundColor Gray
        }
        Write-Host ''
        $ProfileName = Read-Host '  Enter the Outlook profile name to clean'
        if ([string]::IsNullOrWhiteSpace($ProfileName)) {
            Write-Host '  ERROR: A profile name is required when multiple profiles exist.' `
                       -ForegroundColor Red
            Write-Host ''
            exit 1
        }
    }
    else {
        # No Outlook profile found in the registry at all -- real problem,
        # not something to paper over with a fallback.
        Write-Host '  ERROR: No Outlook profile found on this machine.' -ForegroundColor Red
        Write-Host ''
        exit 1
    }
}

# Validate/normalize against the real registered profiles -- applies
# whether $ProfileName came from -ProfileName, auto-detect, or the prompt
# above. Case-insensitive match, but the matched profile's ACTUAL
# registered casing is what gets used from here on (e.g. typing
# "restorerules" resolves to the real "RestoreRules"), so the CSV
# filename, Outlook COM Logon(), and all log/console output stay
# consistent with what Script 00 itself would have produced.
$matchedProfile = $foundProfiles | Where-Object { $_.Name -eq $ProfileName } | Select-Object -First 1
if (-not $matchedProfile) {
    Write-Host "  ERROR: '$ProfileName' does not match any Outlook profile on this machine." `
               -ForegroundColor Red
    if ($foundProfiles.Count -gt 0) {
        Write-Host '  Available profiles:' -ForegroundColor Yellow
        foreach ($p in $foundProfiles) {
            Write-Host "    - $($p.Name)" -ForegroundColor Gray
        }
    }
    Write-Host ''
    exit 1
}
$ProfileName = $matchedProfile.Name

$profileName = $ProfileName
$Global:OMMigrate.Settings.OutlookProfile.SelectedProfile = $ProfileName

Write-Host "  Profile          : $profileName" -ForegroundColor Gray

# -- Confirm before proceeding --------------------------------------------------
# Gives an explicit way out (including when a single profile was
# auto-selected with no prompt) before locating the CSV or touching Outlook.
# In -WhatIf mode, Confirm-Action auto-confirms (no prompt) since nothing
# destructive happens -- consistent with existing OMMigrate WhatIf behavior.
$proceed = Confirm-Action -Message "Remove duplicate rules for profile '$profileName'?"
if (-not $proceed) {
    Write-Host '  Cancelled -- no changes made.' -ForegroundColor Yellow
    Write-Host ''
    exit 0
}

# -- Locate DuplicateRules_<Profile>.csv ---------------------------------------
# Profile-suffixed report filename -- reuses Get-OMMigrateCsvPath's existing
# suffix/sanitize logic via -BasePathOverride, pointed at ReportPath instead
# of its default ConfigPath. Must match what OMMigrate-FindDuplicateRules.ps1
# wrote for this same profile.
$csvPath = Get-OMMigrateCsvPath -BaseName 'DuplicateRules.csv' `
                                -BasePathOverride $Global:OMMigrate.ReportPath
if (-not (Test-Path $csvPath)) {
    Write-Host '  ERROR: DuplicateRules file not found.' -ForegroundColor Red
    Write-Host "  Expected: $csvPath" -ForegroundColor Yellow
    Write-Host '  Either:' -ForegroundColor Yellow
    Write-Host "    - OMMigrate-FindDuplicateRules.ps1 hasn't been run yet for this profile, or" `
               -ForegroundColor Yellow
    Write-Host '    - it was run and found no duplicates (no file is written in that case).' `
               -ForegroundColor Yellow
    Write-Host "  Run OMMigrate-FindDuplicateRules.ps1 -ProfileName `"$profileName`" to check." `
               -ForegroundColor Yellow
    Write-Host ''
    exit 1
}

$toDelete = Import-Csv -Path $csvPath -Encoding UTF8
Write-Host "  Loaded $($toDelete.Count) rule(s) from $(Split-Path $csvPath -Leaf)." -ForegroundColor Cyan
Write-Host ''

# -- Connect to Outlook -------------------------------------------------------
$outlook   = $null
$namespace = $null
try {
    Add-Type -AssemblyName 'Microsoft.Office.Interop.Outlook' -ErrorAction SilentlyContinue
} catch { }

try {
    $outlook   = New-Object -ComObject Outlook.Application
    $namespace = $outlook.GetNamespace('MAPI')
    $namespace.Logon($profileName, $null, $false, $true)
}
catch {
    Write-Host "  ERROR: Could not connect to Outlook: $_" -ForegroundColor Red
    Write-OMMigrateLog -Message "RemoveDuplicateRules: Outlook connection failed: $_" -Level ERROR
    exit 1
}

# -- Group by StoreName and delete --------------------------------------------
$byStore      = $toDelete | Group-Object StoreName
$totalDeleted = 0
$totalFailed  = 0

foreach ($storeGroup in $byStore) {
    $storeName = $storeGroup.Name
    $ruleNames = @($storeGroup.Group | Select-Object -ExpandProperty RuleName)

    Write-Host ('  ' + ('=' * 54)) -ForegroundColor DarkCyan
    Write-Host "  Store: $storeName" -ForegroundColor White
    Write-Host ('  ' + ('=' * 54)) -ForegroundColor DarkCyan

    # Find the store
    $targetStore = $null
    try {
        $stores = $namespace.Stores
        for ($s = 1; $s -le $stores.Count; $s++) {
            $st = $stores.Item($s)
            if ($st.DisplayName -eq $storeName) {
                $targetStore = $st
                break
            }
        }
    } catch { }

    if (-not $targetStore) {
        Write-Host "    [SKIP] Store not found: $storeName" -ForegroundColor Yellow
        $totalFailed += $ruleNames.Count
        continue
    }

    $rules = $null
    try { $rules = $targetStore.GetRules() } catch { }

    if (-not $rules) {
        Write-Host "    [SKIP] Could not get rules for: $storeName" -ForegroundColor Yellow
        $totalFailed += $ruleNames.Count
        continue
    }

    $deleted = 0
    foreach ($ruleName in $ruleNames) {
        if ($WhatIf) {
            Write-Host "    [PREVIEW] Would delete: '$ruleName'" -ForegroundColor DarkGray
            $deleted++
            $totalDeleted++
            continue
        }

        try {
            $rules.Remove($ruleName)
            Write-Host "    [DELETED] '$ruleName'" -ForegroundColor Green
            $deleted++
            Write-OMMigrateLog -Message "Removed duplicate rule '$ruleName' from '$storeName'." `
                               -Level INFO
        }
        catch {
            Write-Host "    [FAILED]  '$ruleName': $_" -ForegroundColor Red
            $totalFailed++
            Write-OMMigrateLog -Message "Failed to remove '$ruleName' from '$storeName': $_" `
                               -Level WARN
        }
    }

    # One Save() per store after all deletions -- atomic per Gemini pattern
    if ($deleted -gt 0 -and -not $WhatIf) {
        try {
            $rules.GetType().InvokeMember(
                'Save',
                [System.Reflection.BindingFlags]::InvokeMethod,
                $null, $rules, @($true)
            )
            Write-Host "    Saved: $deleted rule(s) deleted." -ForegroundColor Green
            $totalDeleted += $deleted
            Write-OMMigrateLog -Message "Rules saved for store '$storeName': $deleted deleted." `
                               -Level INFO
        }
        catch {
            Write-Host "    [WARN] Save failed for '$storeName': $_" -ForegroundColor Yellow
            Write-OMMigrateLog -Message "Save failed after deletion on '$storeName': $_" `
                               -Level WARN
        }
    }
    Write-Host ''
}

try { $namespace.Logoff() } catch { }
try {
    [System.Runtime.InteropServices.Marshal]::ReleaseComObject($namespace) | Out-Null
    [System.Runtime.InteropServices.Marshal]::ReleaseComObject($outlook)   | Out-Null
} catch { }

# -- Summary ------------------------------------------------------------------
Write-Host ''
if ($WhatIf) {
    Write-Host "  [PREVIEW] Would delete $totalDeleted rule(s)." -ForegroundColor Yellow
}
else {
    Write-Host "  Done. Deleted=$totalDeleted Failed=$totalFailed" `
               -ForegroundColor $(if ($totalFailed -gt 0) { 'Yellow' } else { 'Green' })
    Write-OMMigrateLog -Message "RemoveDuplicateRules complete: Deleted=$totalDeleted Failed=$totalFailed" `
                       -Level INFO
    if ($totalDeleted -gt 0) {
        Write-Host ''
        Write-Host "  Delete $(Split-Path $csvPath -Leaf) from the Reports folder -- it is now stale." `
                   -ForegroundColor Gray
        Write-Host "  Path: $csvPath" -ForegroundColor Gray
    }
}
Write-Host ''

# ***** END OF FILE *****
