blank_issues_enabled: false
contact_links:
  - name: Questions and General Discussion
    url: https://github.com/SC-Admin567/OMMigrate/discussions
    about: For open-ended questions or discussion that doesn't fit a bug report or feature request, use Discussions instead.
